### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode.Web#10]
I started a small project with Pode.Web for searching Exchange with Get-MessageTrackingLog https://github.com/ili101/ExchangeMessageTrackingLogWeb.
I want to add an Excel download button to the WebTable like the embedded "Export" (CSV) one.
I made [a WebSection with a button](https://github.com/ili101/ExchangeMessageTrackingLogWeb/blob/818b62fc234bfbb30b6323bcaadf4ab1e8e7d7f4/Home.ps1#L14-L21) and moved the data to it with `Get-PodeState` but I don't know if it's the best way to do it or what to do from here.
Something like save the file to some temporary folder and link the button to it and then delete it? 
Can you help? (If you like to test it the code by default doesn't need Exchange, it use dummy data for tests)
![image](https://user-images.githubusercontent.com/6960531/103176704-b123f380-487c-11eb-8a61-c43b046403e3.png)

**Comment by Badgerati** [comment]
That's actually a neat way of doing it! As it stands at the moment I can't really think of another way.

The only other idea is that in 0.3.0 (#8), tables are now their own element and the refresh/export buttons belong to each table. Maybe we could have a `New-PodeWebTableButton` which allows you to add new meta buttons to a table 🤔 And that button's scriptblock is sent the table's current viewable data.

To download the file, via your current button or the above idea, you should be able to do `Set-PodeResponseAttachment` in the button's scriptblock, and point to the file created by `Export-Excel` - later deleting the file at some point (not straight away).

**Comment by ili101** [comment]
Tried but didn't manage to get it working from the button, File is not downloaded. Not sure what is missing.
https://github.com/ili101/ExchangeMessageTrackingLogWeb/commit/696441dedd5766f0f5a788581cbf101f21d9e843
Also tried `Move-PodeResponseUrl` I think the browser downloads it but not showing the download popup.

**Comment by Badgerati** [comment]
Two things on this one, first I've fixed why both `Set-PodeResponseAttachment` and `Move-PodeResponseUrl` weren't working in the `develop` branch.

Also, in your script when saving/exporting the Excel file, the path will need to be joined onto the server path:

```powershell
$path = Join-Path (Get-PodeServerPath) '.\Storage\test.xlsx'
Export-Excel -InputObject $global:Results -WorksheetName 'Log' -TableName 'Log' -AutoSize -Path $path
```

^ and that should do it 😄

**Comment by ili101** [comment]
It works with csv file but when using xlsx the file get corrupted.
On disk it's saved ok, browsing to the URL manually in the browser download correctly but downloaded copy by clicking the button is re-encoded or something.
https://github.com/ili101/ExchangeMessageTrackingLogWeb/blob/6ca939ab5cc2a7f9252efd8edb7dc1ac3f755863/Home.ps1#L95-L96

**Comment by Badgerati** [comment]
Managed to reproduce it, what's in develop now lets me download excel files.
