### ISSUE TITLE
Pode.Web Tutorial page is hosed.

### ISSUE THREAD

**Issue by rob3rt-keating** [Badgerati/Pode.Web#113]
1)  https://badgerati.github.io/Pode.Web/Getting-Started/Tutorials/Basics
Icons consume **entire** browser page.

2) All links to pages (i,e New-PodeWebIcon, etc) return 404

**Comment by Badgerati** [comment]
Hey @rob3rt-keating,

The link which I'm guesing you've clicked is wired up wrong and should be pointing at https://badgerati.github.io/Pode.Web/Tutorials/Basics/ - this is fixed in #61/v0.5.0 and should be out very soon.

**Comment by Badgerati** [comment]
v0.5.0 has now been released, and the link causing the issue has now being fixed. If it's still an issue please feel free to re-open.
