### ISSUE TITLE
Feature Request: Add support to switch themes on the fly via button/scriptblock

### ISSUE THREAD

**Issue by the-mentor** [Badgerati/Pode.Web#115]
pretty much what the title says.

**Comment by Badgerati** [comment]
This is something I have considered before, like a quick toggle at the top between light/dark themes - maybe allow it to be customised so it could be dark/terminal etc 🤔 

Or, a drop down of all available themes perhaps?

**Comment by Badgerati** [comment]
From Gitter: Instead of a toggle, add a new `Update-PodeWebTheme` output action to update the theme on the client-side and refresh the page.

**Comment by Badgerati** [comment]
Added two new output actions for themes:

* `Update-PodeWebTheme` - which will let you change the theme on the frontend via the pode.web.theme cookie
* `Reset-PodeWebTheme` - which will clear the cookie, and reset the user's theme back to the server's default theme
