### ISSUE TITLE
Feature Request: Publish a folder and all files under it.

### ISSUE THREAD

**Issue by the-mentor** [Badgerati/Pode.Web#116]
This is useful when you need to add assets to your site like images, videos, documents, application and other files.

And linking to them in the following ways
- linking to an image within the site.
- adding a download button to download a file 
- embedding a video on a page from the published directory

**Comment by Badgerati** [comment]
Hey @the-mentor,

Are you talking about something like the `/public` folder and custom static routes? https://badgerati.github.io/Pode/Tutorials/Routes/Utilities/StaticContent/

**Comment by the-mentor** [comment]
@Badgerati I got the public folder working so this is an existing feature.

Thanks.
