### ISSUE TITLE
Scoping Question: How to pass object to element scriptblock?

### ISSUE THREAD

**Issue by kort3x** [Badgerati/Pode.Web#121]
Let's say i want to pass an obect to a table to display it, what would be the correct way?

`using:` does not work, apparently.
Only way i found is to make the object global but.. you know...

**Comment by Badgerati** [comment]
Hey @kort3x,

You can pass the object to `-ArgumentList` and then access it via the params block on your `-ScriptBlock`:

```powershell
$myObject = @{}

New-PodeWebTable -Name 'TableName' -ArgumentList $myObject -ScriptBlock {
    param($myObject)
    # logic
}
```

This does mean the object will always be the same, if it is then this is good 😃 if it's expected to change, it would be better loading the object within the scriptblock so its fresh each time.
