### ISSUE TITLE
Feature Request: Add -collapsed parameter to Accordion

### ISSUE THREAD

**Issue by kort3x** [Badgerati/Pode.Web#122]
Would be nice to be able to create an accordion which is copletly collabsed on page load.

**Comment by Badgerati** [comment]
Definitely! I'll look into it :D

**Comment by Badgerati** [comment]
The above commit adds a new `-Mode` parameter to `New-PodeWebAccordion`, allowing you to toggle between Normal, Collapsed, and Expanded modes on page start - Normal is the default:

```powershell
New-PodeWebAccordion -Mode Collapsed -Bellows @(...)
```

**Comment by kort3x** [comment]
awesome - thank you
