### ISSUE TITLE
No sidebar / StartHiddenSideBar

### ISSUE THREAD

**Issue by PrzemyslawKlys** [Badgerati/Pode.Web#125]
It would be a great option to have the ability to be able to have no side bar completely or have it start hidden (reverse what is now possible).

**Comment by Badgerati** [comment]
Added a new `-HideSidebar` switch `Use-PodeWebTemplates`:

```powershell
Use-PodeWebTemplates -Title 'Example' -Theme Dark -HideSidebar
```

This will hide the sidebar by default, instead of being shown by default.
