### ISSUE TITLE
ConvertTo-PodeWebPage -Module DBATools : You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by JoelMiller74** [Badgerati/Pode.Web#128]
I am new to using Pode.web but not new to Powershell. I am very interested in using Pode.web to automatically build a web interface to execute powershell functions in a module.
I just ran across ConvertTo-PodeWebPage. This appears to work perfectly for the example of the Powershell Module 'Pester'. 
https://badgerati.github.io/Pode.Web/Tutorials/Pages/
However, When I try to use the same code and use the Module 'DBATools', I get the following error:

```
InvalidOperation: C:\Users\jmill\Documents\PowerShell\Modules\Pode.Web\0.4.1\Public\Pages.ps1:457:9
Line |
 457 |          $paramDefs = $ast.FindAll({ $args[0] -is [System.Management.A …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
```
Here is the code I am running:

```
Import-Module -Name Pode.Web

Start-PodeServer {
    # add a simple endpoint
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http

    # set the use of templates
    Use-PodeWebTemplates -Title 'DBATools'

    # convert module to pages
    ConvertTo-PodeWebPage -Module Pester -GroupVerbs
}
```

**Comment by Badgerati** [comment]
Ooo that is interesting, it would suggest there are functions in that module with no ScriptBlocks - or it could be detecting aliases possibly 🤔 I'll try and grab the DBATools module this weekend and test.

Thanks!

**Comment by JoelMiller74** [comment]
Thanks! There are over 500 public functions in that one. It is a great team that develops it. I can definitely work with them if something needs to be modified on that side. They are very meticulous in writing a very standardized and full-featured PowerShell module with very good test coverage.

**Comment by Badgerati** [comment]
The above commit should now fix it 😄 It wasn't playing ball with cmdlets or functions containing nested functions where parameter names were the same, but should handle both gracefully now - I installed the module and the page building works for me :)

**Comment by JoelMiller74** [comment]
I apologize. I use bitbucket normally (business). I do not see any issues with the change you made. However, I cannot find a good way to test your commit myself in Github. I do not have an issue with you merging to master with the code you have. However, if you have some feedback on how I can test the commit, I will be more than happy to.
Thanks again!

**Comment by Badgerati** [comment]
I have tested with dbatools locally and the pages do render now, so if you're happy with that I can push it with the next release. However, if you'd like to test you should be able to copy the content of the file (https://github.com/Badgerati/Pode.Web/blob/db517c6674257f7e343ad1201ae9aef45e5fef72/src/Public/Pages.ps1), and paste it into your installed Pode.Web module's `/Public/Pages.ps1` file :)

**Comment by JoelMiller74** [comment]
I tried this in Powershell 7.1.3 and Windows Powershell 5.1. Both produced the same error below. I tried remove-module pode.web and reimporting again even with -force.

```
Get-PodeWebPagePath: C:\Users\jmill\Documents\PowerShell\Modules\pode.web\0.4.1\Public\Pages.ps1:320:16
Line |
 320 |          Url = (Get-PodeWebPagePath -Name $Name -Group $Group)
     |                 ~~~~~~~~~~~~~~~~~~~
     | The term 'Get-PodeWebPagePath' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was
     | included, verify that the path is correct and try again.
```

**Comment by Badgerati** [comment]
Oh! I've just realised the version of Pode.Web you're using - if you're able to, upgrade to the new v0.5.1 and paste the page in again. Or, if you can't then you'll have to manually copy in the edits from the commit's diff into the Pages.ps1 file.

**Comment by JoelMiller74** [comment]
Thanks and good catch. That was the issue. I updated both Pode and Pode.web locally and that resolved the issue.
This is working properly for DBATools.
I really appreciate the quick responses.
