### ISSUE TITLE
Feature Request: A alternnative display text 

### ISSUE THREAD

**Issue by AndreasNick** [Badgerati/Pode.Web#161]
Hello Matthew,

I experimented a bit with the text elements because I want different screen texts. For example, to simplify parameters for complex texts but also to enable multilingual web pages. That's why I'm putting this here as a "feature request" and also supplying some code. I may even be able to gradually incorporate this into other functions and generate "pull requests" for this. So, if there is interest. The whole thing can take me a few weeks if I implement something like this.

New parameter "DisplayText" can be $null

```
$DisplayText = @{
 Terms = "Bedingungen"
 Privacy = "Privatsphäre"
 Name = "Einstellungen"
}

New-PodeWebCheckbox2 -Name 'Settings' -Options @('Terms', 'Privacy') -AsSwitch -DisplayText $DisplayText
```

The function  New-PodeWebCheckbox2 has a nw parameter  **[Hashtable] $DisplayText,** 

```
 return @{
        ComponentType = 'Element'
    ...
        Name = $Name
        DisplayText = $DisplayText
     ...
   }
```

```
The Pode element "checkbox2.pode have new element to translate the strings:

```
   
	$(
		if ($null -ne $data.DisplayText -and $data.DisplayText['Name']) {
			"<div class='col-sm-2 col-form-label'>$($data.DisplayText['Name'])</div>"
		}
		else {
			"<div class='col-sm-2 col-form-label'>$($data.Name)</div>"
		}
	)
```

And as alternative solution the function GDT (Get-DisplayText)


		    #Get-DisplayText
		    function GDT
			{
				param([String] $Text)
				if ($null -ne $data.DisplayText -and $data.DisplayText[$Text]){
					return $($data.DisplayText[$Text])
				} else {
					return $Text
				}
			}
...

  $(if ($data.Options[$i] -ine 'true') { GDT($data.Options[$i]) })

**Comment by Badgerati** [comment]
Hey @AndreasNick,

I like the idea! This could be something useful for all of the form elements. I'm wondering if it'll be worth having a `-DisplayName` for each of the elements instead, and then for elements like Select/Radio/Checkbox a `-DisplayOptions` which is the hashtable in your example above.

Credentials, DataTime and MinMax will also need tweaking, as their "Username" or "Date" labels/placeholders are hardcoded currently 🤔

**Comment by AndreasNick** [comment]
If you have a plan, I can gladly invest time and implement that with :-) My point was to enable a multilingual view. The format for a date etc. I have not thought.  But of course that is also part of it.

**Comment by Badgerati** [comment]
I've added a new `-DisplayName` to the following elements, which when supplied, this name will be displayed on the page instead (`-Name` is still required):

* Textbox
* FileUpload
* Checkbox
* Radio
* Select
* Range
* Credential
* DateTime
* MinMax

Checkboxes, Radio, and Select have also had a new `-DisplayOptions` added, which will display these options on the page instead (`-Options` is still required). For Select elements, `Update-PodeWebSelect` now also has a `-DisplayOptions` parameter, as well as a `-SelectedValue` parameter.

In the case of both `-DisplayName` and `-DisplayOptions`, these are the values that will be displayed visually to users (if not supplied, then `-Name`/`-Options` are displayed by default). On the backend, when a form is submitted say, the values sent back to the server are the original `-Name` and `-Options` values; this is done so `$WebEvent.Data['<element-name>']` works regardless of what's displayed:

```powershell
New-PodeWebForm -Name 'New User' -ScriptBlock {
    $name = $WebEvent.Data.Name
    $role = $WebEvent.Data.Role
} -Content @(
    New-PodeWebTextbox -Name 'Name' -DisplayName 'Nom'
    New-PodeWebSelect `
        -Name 'Role' `
        -DisplayName 'Rôle' `
        -Options @('Developer', 'Admin', 'Operations') `
        -DisplayOptions @('Développeur', 'Administrateur', 'Opérations')
)
```

![image](https://user-images.githubusercontent.com/1483395/142775202-0b326601-3870-4f62-a2e7-314363aab64a.png)

The Credentials element has also been updated with `-PlaceholderUsername` and `-PlaceholderPassword` parameters.
