### ISSUE TITLE
Suggestion -  bootswatch support

### ISSUE THREAD

**Issue by mintminttea** [Badgerati/Pode.Web#17]
Suggest to support bootswatch from https://bootswatch.com in theme.
This could be easily done with switching with the theme name by changing the css or cdn url.
```
Use-PodeWebTemplates -Title 'Some Title' -Theme cyborg
```

**Comment by Badgerati** [comment]
I probably won't support bootswatch internally, as some themes will require custom logic to work properly, but this could be a good chance to get custom themes setup. Something like:

```powershell
Use-PodeWebTemplates -Title Example -Theme Custom

Add-PodeWebCustomTheme -Name Cyborg -Url 'https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/cyborg/bootstrap.min.css'
Add-PodeWebCustomTheme -Name Lux -Url 'https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/lux/bootstrap.min.css'
```

If there are multiple, the first custom theme is the default.
