### ISSUE TITLE
No Start-PodeServer function

### ISSUE THREAD

**Issue by alaurie** [Badgerati/Pode.Web#182]
Am I missing something? Docs say to use Start-PodeServer however according to Get-Command and the error when you run the script the function does not exist.

**Comment by kort3x** [comment]
Start-PodeServer is part of pode not pode.web

[https://github.com/Badgerati/Pode](url)

**Comment by Badgerati** [comment]
Hey @alaurie,

What @kort3x said :) `Start-PodeServer` is a function found in the main [Pode](https://github.com/Badgerati/Pode) module; Pode.Web is an extension module for Pode.
