### ISSUE TITLE
Feature Request: Use ID from form field in $WebEvent.Data

### ISSUE THREAD

**Issue by Veers01** [Badgerati/Pode.Web#184]
First, I want to say that I really like the Pode and Pode.Web module. This is a very usefull tool to do web interface for powershell script.

I have a suggestion for improving the usability of $webEvent.Data. If the -ID parameter is set in form element (textbox, checkbox...), use it as the key for the $webEvent.Data object. At this time, it use the name but this is also the name used to describe the field in the webpage. When you want to use special character, this is tricky.

Thank you.

**Comment by Badgerati** [comment]
Hey @Veers01,

This could likely be resolved via #161, which could let you specify a `-DisplayName` for form elements which changes what gets changed on the page, while keeping the `-Name` in HTML and what you reference in `$WebEvent.Data` the same.

I could add a new `-IDAsKey` switch for form elements to change the reference key in the data hashtable, and this would keep from breaking people's current integrations.

**Comment by Veers01** [comment]
Hi @Badgerati 

You are right, having a -DisplayName or a -Caption will do it and could be useful for other thing like #161. The Idea is to separate the identifier from the text show in the webpage.

Thank you!

**Comment by Veers01** [comment]
Duplicate of #161
