### ISSUE TITLE
Feature Request: Use name/value parameter for New-PodeWebCheckbox 

### ISSUE THREAD

**Issue by Veers01** [Badgerati/Pode.Web#185]
Hi!

This will be useful to use a name-value parameter for the checkbox. 

Ex: New-PodeWebCheckbox -Name 'Voicemail' -ID 'Voicemail' -Checked $true -AsSwitch

Since most of the time you want to set the checkbox from a existing boolean value, that will be faster to use.

Thank you.

**Comment by Badgerati** [comment]
Hey @Veers01,

Do you mean change the `-Checked` switch to a `[boolean]` parameter?

If so, you can pass a value for a switch as follows:
```powershell
New-PodeWebCheckbox -Name 'Voicemail' -ID 'Voicemail' -Checked:$true -AsSwitch

# or

$myVariable = $false
New-PodeWebCheckbox -Name 'Voicemail' -ID 'Voicemail' -Checked:$myVariable -AsSwitch
```

😃

**Comment by Veers01** [comment]
Hey, now I feel like I should RTFM... I think I will do some more digging before submitting new Feature Request :)
