### ISSUE TITLE
Sorting the Pages Menu on the left

### ISSUE THREAD

**Issue by hvoges** [Badgerati/Pode.Web#199]
Is there a way to sort the Pages Menu on the left? When I add new Pages with new-PodeWebPage, the Page-Links are added in random order.

**Comment by Badgerati** [comment]
Yep, it was a bug :)

That above commit fixes the sorting of pages so they're now:
![image](https://user-images.githubusercontent.com/1483395/142056285-97194055-8097-4abb-a75b-60ca3ed4c421.png)
