### ISSUE TITLE
Usage about Modal 

### ISSUE THREAD

**Issue by mintminttea** [Badgerati/Pode.Web#23]
Hi, 
I need some help how to pass the data to Modal element and not sure what to do.
What I am trying to do is a confirm button from delete action in the podewebtable and show as Modal as form and let user confirm while passing the item information to modal.
Take the full.ps1 as example.
Here I add the modal element to the  Add-PodeWebPage page together.
```
$modal = New-PodeWebModal -Name 'Edit Service' -Id 'modal_edit_svc' -AsForm -Content @(
        New-PodeWebAlert -Type Info -Value 'This does nothing, it is just an example'
        New-PodeWebCheckbox -Name Running -Id 'chk_svc_running' -AsSwitch
    ) -ScriptBlock {
        $WebEvent.Data | Out-Default
        Hide-PodeWebModal
    }
````
And the button inside table.
```
Show-PodeWebModal -Id 'modal_edit_svc' -DataValue $WebEvent.Data.Value -Actions @(
                Out-PodeWebCheckbox -Id 'chk_svc_running' -Checked:$checked
            )
```

1. What is the usage of -DataValue of Show-PodeWebModal? It seems like passing a value to modal_edit_svc but not sure how to call it.
2. I got empty result of $WebEvent.Data | Out-Default in New-PodeWebModal ScriptBlock , is it showing only the content as form inside New-PodeWebModal?
Thanks.

**Comment by Badgerati** [comment]
Hey,

`-DataValue` on `Show-PodeWebModal` sets a `pode-data-value` attribute on the modal HTML element. This value is then sent in the Request when the modal's Submit button is clicked - so if the DataValue is the name of a service, it's a way of passing the service from table > modal > submit.

`$WebEvent.Data | Out-Default` shouldn't be empty, at a minimum it should have a `Value` entry from the `-DataValue`. The checkbox/switch in the full.ps1 example will need to be checked for the form to send its value through. I just tried it on develop, and the DataValue and Checkbox were both sent through 🤔

**Comment by mintminttea** [comment]
I understand now, I tried to put the item ID in data value for every button in loop and it got blank result.
Now I switch to $WebEvent.Data.value and now it is passing the DataColumn of podewebtable to modal $webevent.data.😀
Is it possible to pass the data to Elements inside modal too?

**Comment by kort3x** [comment]
> Is it possible to pass the data to Elements inside modal too?

I got the same question.

**Comment by Badgerati** [comment]
Hey!

Yes, it's possible; when you call `Show-PodeWebModal` there are `-Actions` you can supply - such as `Out-PodeWebText` etc. These actions run just prior to the modal showing, and will populate elements for you.

I'm still going through and writing up the documentation, but this should be of some help 😄  https://github.com/Badgerati/Pode.Web/blob/Issue-3/docs/Tutorials/Layouts/Modal.md

**Comment by Badgerati** [comment]
Documentation for modals is now up [here](https://badgerati.github.io/Pode.Web/Tutorials/Layouts/Modal/) 😃
