### ISSUE TITLE
Add-PodeWebPage groups with spaces breaking nav expansion

### ISSUE THREAD

**Issue by robinmalik** [Badgerati/Pode.Web#255]
Hi,

Sorry for opening another issue!

For visual clarity, supporting page groups in the left hand navigation pane with spaces in would be nice. For example:

![image](https://user-images.githubusercontent.com/8790561/147669139-60628f53-2c2b-4fc0-b489-926948ac61b8.png)

Unfortunately whilst Pode.Web currently renders this correctly visually, it breaks the bootstrap collapse/expand behaviour because of spaces in various attributes (e.g. `id` where spaces are invalid). I've had to work around this on a product built at work and the decision was to replace spaces with hyphens when rendering the code.

Doing this on the associated `id`, `href`, `pode-page-group` and `aria-controls` attributes seems to fix this, whilst leaving `<span class="h6">My Group</span>` to display as desired.

Would you like me to attempt to resolve this and open a pull request?

**Comment by Badgerati** [comment]
Hey @robinmalik,

Go for it 😄 I would say that `pode-page-group` could probably stay as is, as it's only for URL/AJAX calls, and shouldn't affect group expanding.
