### ISSUE TITLE
Array-Members are lost during handover to Scriptblock

### ISSUE THREAD

**Issue by hvoges** [Badgerati/Pode.Web#256]
Hi Matthew, 
I have a rather strange behaviour here I cannot explain. I created an array of PSCustomobjects and handed them over to a PodeWebPage via -Argumentlist, but inside the Scriptblock, only the first element of the array is visible. Is this intended?

    Start-PodeServer -Threads 4 -scriptblock {

        Use-PodeWebTemplates -Title 'Rauminstallation' -Theme Light
        Add-PodeEndpoint -Address * -Port 80 -Protocol Https 
        [Array]$Jobs = 1..5 | 
            ForEach-Object {
                [PSCustomObject]@{
                    JobName = $_
                    JobID = $_
                    JobDefinition = { "Hello World" }
                }
            }
   
      Add-PodeWebPage -Name Jobs -Title Jobs -Icon cogs -ArgumentList $Jobs -Scriptblock {
          Param( [array]$Jobs )

          $Jobs | % { Write-Host $_.JobName } 

          New-PodeWebContainer -Content @(
              New-PodeWebGrid -Vertical -cells @(
                  New-PodeWebCell -Content @(
                      New-PodeWebSelect -Name Job -Options @( $Jobs.Jobname )
                  )
              )
          )    
      }
    }

**Comment by Badgerati** [comment]
Hi @hvoges,

The `-ArgumentList` itself takes an array of objects, and then splats those items onto the `-ScriptBlock`. This means the `param(..)` will be getting 5 items: `param($job1, $job2, $job3, $job4, $job5)`.

To pass a whole array, you should be able to do: `-ArgumentList @(,$Jobs)`, and that will pass the array as a whole as just `param($jobs)`.

**Comment by hvoges** [comment]
Silly to ask the same question twice - thank you for not reminding me of that. :-)
