### ISSUE TITLE
Forms with Scriptblock

### ISSUE THREAD

**Issue by hvoges** [Badgerati/Pode.Web#258]
Hi @Badgerati,
I am trying to execute a Scriptblock after a user chose a value from a select-Element and pressed a button. As it it not possible to access the Select-Element directly, I wonder if a Form could do the trick.  The Submit-Button could execute a Script instead of invoking a Get or a Post.

**Comment by Badgerati** [comment]
Hi @hvoges,

A button with a scriptblock would still invoke a Post, similar to a Form's Submit button - just the Form would also send the Select's value as well to a Form's `-ScriptBlock`.

Using events on a Select element's change event should also do the same, and remove the need for a button (if it's not 100% needed): https://badgerati.github.io/Pode.Web/Tutorials/Events/

**Comment by Badgerati** [comment]
This appears that it will be covered by #457 - closing.
