### ISSUE TITLE
Unable to run the examples - issue in helpers.ps

### ISSUE THREAD

**Issue by abhi18av** [Badgerati/Pode.Web#259]
Hi @Badgerati ,

Thanks for the wonderful project!

I am running into the following error while going through the examples

```
PS /home/abhinav/projects/podeapp> pode start
Split-Path: /home/abhinav/.local/share/powershell/Modules/Pode.Web/0.7.0/Private/Helpers.ps1:3
Line |
   3 |  … $path = Split-Path -Parent -Path ((Get-Module -Name 'Pode.Web').Path)
     |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.


```

I'm not completely sure why this might be happening, but from `Get-Module -Name 'Pode.Web'` it seems that the Path is expected and it doesn't exist.

I have made sure to install (and re-install later) the `Pode.Web` module 

```
 Install-Module -Name 'Pode.Web' -Force

```

However, it doesn't seem to be making a difference.

Could you please help me out on this?

**Comment by Badgerati** [comment]
HI @abhi18av,

If you're using `pode start`, make sure any `Import-Module` calls have `-Scope Global` :)

**Comment by abhi18av** [comment]
Ah, silly me - yes after that addition everything is working as expected - thanks for tip Matthew!
