### ISSUE TITLE
New-PodeWebTable -ArgumentList $arg can not be used with changing values

### ISSUE THREAD

**Issue by David54236** [Badgerati/Pode.Web#260]
Hi Pode.Web-Team,

I am trying to create a page that displays different tables with different values depending on the $WebEvent.Query.Value.

This is my code:

```
Add-PodeWebPage -Name 'Repository' -Icon 'database-eye' -ScriptBlock {
if($WebEvent.Query.Value)
    {
        $dataType = $WebEvent.Query.Value

        New-PodeWebTable -Name 'Objects' -DataColumn "Id" -SimpleFilter -ArgumentList $dataType -ScriptBlock {
            param($dataType)

            $uri = 'SOME URI' + $dataType
            $objects = (Invoke-RestMethod -Method Get -Uri $uri).Documents

            foreach ($object in $objects)
            {
                # CODE
            }
        }
    }
# CODE
}
```

The $dataType Vairable in the New-PodeWebTable ScriptBlock is only set on the very first call. Is this behavior the way you want it to be? Or am I doing something wrong?

**Comment by Badgerati** [comment]
Hi @David54236,

When `New-PodeWebTable` is called it creates a route under the hood; to prevent millions of 1 time routes being created, the route is created once (with the arguments supplied), and then skipped thereafter.

However, within the `-ScriptBlock` of `New-PodeWebTable` it will also have access to `$WebEvent.Query.Value` :)

Something like the following should work the same:
```powershell
Add-PodeWebPage -Name 'Repository' -Icon 'database-eye' -ScriptBlock {
    if ($WebEvent.Query.Value)
    {
        New-PodeWebTable -Name 'Objects' -DataColumn "Id" -SimpleFilter -ScriptBlock {
            $uri = 'SOME URI' + $WebEvent.Query.Value
            $objects = (Invoke-RestMethod -Method Get -Uri $uri).Documents

            foreach ($object in $objects)
            {
                # CODE
            }
        }
    }
    # CODE
}
```

Hope that helps!

**Comment by David54236** [comment]
That helps a lot, thanks for the quick answer.

One more small question, what would you say is generally the best way to use variables from the PodeWebPage ScriptBlock in the PodeWebTable ScriptBlock? 

I've read about the different scopes like $state: and $session: and the Set-PodeState function, but am a little confused as to when what can and should be used and how.

If you could still help me here I would be very grateful.

Thank you! :-)

**Comment by Badgerati** [comment]
Hi @David54236,

No worries :)

State variables are for sharing global server variables across all the different runspaces that Pode uses. You can use this to pass values around, but note that it will affect everybody, not just the current page/user. Usually it's for values like PSSessions, SQL Connections, etc.

Session variables apply to a user's current session, such as filter values, counts, etc. Changes values here only apply to the user.

In general it depends on what the variables are; if it's WebEvent, Session or State; then these are available within the Table anyway. State would be if you wanted to change something server wide, and Session if you want to retain some information for the duration of a user's session.

The `-ArgumentList` is mostly if you're trying to build a number of tables, each with identical scriptblocks, but only a single value changes. Like a foreach loop to make 3 tables for different performance counters - each would have the same scriptblock logic, with only a counter name different.

If there's a script your stuck with and you have an example to post here I can have a look, and there's always the Pode [Discord](https://discord.gg/fRqeGcbF6h) server 😄

**Comment by David54236** [comment]
Thank you very much :)

I'll experiment around a bit more and definitely come back to the offer if I get stuck again.

I also wanted to say that I am a big fan of your work on Pode and Pode.Web.
