### ISSUE TITLE
it supports spa?

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode.Web#265]
Hi @Badgerati 

It supports spa?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

I'm guessing you mean Single-Page Apps? If so, then not currently. You could technically build everything onto the Home page, but if you need all of the dynamic component toggling a SPA normally has, then you can only do some of this at the moment.

**Comment by ericxin1982** [comment]
Thanks for confirmation.
