### ISSUE TITLE
Array from Table ScriptBlock unwrapped

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode.Web#27]
`New-PodeWebTable` "ScriptBlock" output unwrapped. If one of the parameters is "Length" and it's empty (like in the output of `Get-Item` that return one folder for example) it will fail the test in `function New-PodeWebTable` `if (($result.Length -gt 0)`...

Test code will generate no output:
``` powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Protocol Http
    Use-PodeWebTemplates -Title Tools -Theme Auto

    Add-PodeWebPage -Name 'File' -Icon Activity -Layouts @(
        New-PodeWebTable -Name 'Explorer' -Id 'DriveExplorer' -AsCard -ScriptBlock {
            [PSCustomObject]@{
                Name          = '$Item.Name'
                LastWriteTime = '$Item.LastWriteTime.ToString()'
                Length        = ''
            }
        }
    )
}
```

Looks like Pode `Invoke-PodeScriptBlock` unwrapping output twice, once when dot sourcing the scriptblock and once on return so practicably if you want to return an unwrapped array you have to do `, , $Array` [return-an-array](https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7.1#return-an-array)

Fix by adding the missing Array if  missing in `New-PodeWebTable`  [TableUnwrapping](https://github.com/Badgerati/Pode.Web/compare/develop...ili101:TableUnwrapping?expand=1). Alternatively we can change the if check from `if (($result.Length -gt 0) -and [string]::IsNullOrWhiteSpace($result[0].OutputType))` to something else. BTW what this do `$result[0].OutputType`?

This is not a problem when using `Out-PodeWebTable` as you already warping it in an array there.

**Comment by Badgerati** [comment]
`$result[0].OutputType` is a way of checking if the result was already run through `Out-PodeWebTable`. It could fall under the same issue as `.Length` but hopefully less unlikely - could just rename it to `PodeOutputType` 🤔 

As for `.Length`, that check can probably be safely removed for just `.OutputType`

**Comment by ili101** [comment]
Sounds good

**Comment by ili101** [comment]
Just found a similar bug in my code https://github.com/ili101/PWT/commit/a8041c49b3240342404455d9aed1264d310d76b3 😆
Not only they made the size property name "Length" that conflicts with the Length, the `Get-Items` actually returns 2 different data types for files and folders, and on top of that the folder type don't have "Length" property at all and not just a $null property which makes it trigger the Length that get you 1 (or 0 on PS 5.1) 🤦

**Comment by ili101** [comment]
Maybe I'm missing something but `Out-PodeWebTable` output doesn't have "OutputType" property, if you do:
```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Protocol Http
    Use-PodeWebTemplates -Title Tools -Theme Dark
    Add-PodeWebPage -Name 'File' -Icon Activity -Layouts @(
        New-PodeWebTable -Name 'Explorer' -Id 'DriveExplorer' -AsCard -ScriptBlock {
            [PSCustomObject]@{
                Name          = '$Item.Name'
                LastWriteTime = '$Item.LastWriteTime.ToString()'
                Length        = ''
            } | Out-PodeWebTable -Id 'DriveExplorer'
        }
    )
}
```
it will run it through `Out-PodeWebTable` again and corrupt it.
Shouldn't it be something like: `if (!($result -is [hashtable] -and $result.ElementType -eq 'Table' -and $result.Operation -eq 'Output')) `?

**Comment by Badgerati** [comment]
Oops, that `OutputType` was leftover when I changed to Operation/ElementType combo. I tweaked your check slightly to avoid wrapping other output types as a table, and put the same change onto charts as well 😄

**Comment by ili101** [comment]
Reusability is good, works for me 👍
