### ISSUE TITLE
Help making a file explorer

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode.Web#28]
I extended the scope of my test tool repository "ExchangeMessageTrackingLogWeb" to be a tool collection that will hopefully be expanded by me and maybe other contributes?
So I renamed it to [PWT](https://github.com/ili101/PWT) (PowerShell/Pode Web Tools) 😁

The first extra tool I added is "Drive", It shows the file in the "Drive" folder, let you upload, download, delete and open as text.
However I don't know what is the best way to implement subfolders, I save the "DriveWorkingPath" in Session.Data then load from there but every time I go deeper I get an extra `?value=FolderName` in the URL so no good. any advice on a better way to implement?

If you like to try it get https://github.com/ili101/PWT, copy `Config.Example.ps1` to `Config.ps1` and run. then put some files in the `./Storage/Drive` folder for testing.
The Drive Page is in `.\Tools\Drive\DrivePages.ps1`

![image](https://user-images.githubusercontent.com/6960531/107264400-9af87e00-6a4b-11eb-8fdd-5ac6dc48f49c.png)

**Comment by Badgerati** [comment]
That's awesome!

I had a play, very cool! The dupe `?value=` is a bug, and when fixed subfolders seem to work fine with your current logic; only weird one was going back removed `?value` so just refreshed the table.

Could possibly add a `..` to the top of the table 🤔

**Comment by ili101** [comment]
Committed https://github.com/ili101/PWT/commit/9157b5b0e10ca70ab96f65d3367c5563c70e9cf4
```
Get-PwtRootedPath optional Root param and normalize path.
Drive: Added "..".
Drive: Added "New Folder" and "New File".
Drive: Test that path not escapes the Drive root.
Drive: If value is a folder or incorrect remove it from path to prevent refresh unexpected behavior.
```
First I tested the fix and it works as expected. I think you can merge it.
But it still wasn't behaving exactly like I wanted. It have the back arrow after opening the first subfolder that have no use and also if you open a subfolder you get the "value=Foo" in the URL so if you refresh the page it will try to go again to another Foo subfolder.
This 2 things are good if the value is a file but not if it's a folder or incorrect, so I remove the query part from the URL by redirecting in this cases `Move-PodeResponseUrl -Url ($Request.Url.ToString().Split('?')[0])`
Looks like it working nicely now 😄

**Comment by ili101** [comment]
Maybe you can add `New-PodeWebTable -ClickScriptBlock {}`
This will behave exactly like you can use a button like this example but it will be the main click (without changing the URL) and not a button on the line
```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Protocol Http
    Use-PodeWebTemplates -Title Tools -Theme Dark
    Add-PodeWebPage -Name 'File' -Icon Activity -Layouts @(
        New-PodeWebTable -Name 'Explorer' -Id 'DriveExplorer' -AsCard -DataColumn 'Name' -ScriptBlock {
            $ClickButton = New-PodeWebButton -Name 'Link' -Icon 'Link' -IconOnly -ScriptBlock {
                if ($WebEvent.Data.Value -eq 'Name1') {
                    Sync-PodeWebTable -Id 'DriveExplorer'
                }
                elseif ($WebEvent.Data.Value -eq 'Name2') {
                    Move-PodeWebUrl -Url ($Request.UrlReferrer.ToString() + '?value=' + $WebEvent.Data.Value)
                }
                elseif ($WebEvent.Data.Value -eq 'Name3') {
                    Show-PodeWebToast -Message $WebEvent.Data.Value
                }
            }
            for ($i = 1; $i -lt 4; $i++) {
                [PSCustomObject]@{
                    Name  = "Name$i"
                    Date  = (Get-Date).ToString()
                    Click = $ClickButton
                }
            }
        }
    )
}
```
So this give the option to use the main row click like a button on it giving you more options

**Comment by Badgerati** [comment]
Added `-ClickScriptBlock` to `New-PodeWebTable` 😃 

Following now works for me:
```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Protocol Http
    Use-PodeWebTemplates -Title Tools -Theme Dark
    Add-PodeWebPage -Name 'File' -Icon Activity -Layouts @(
        New-PodeWebTable -Name 'Explorer' -Id 'DriveExplorer' -AsCard -Click -DataColumn 'Name' -ScriptBlock {
            for ($i = 1; $i -lt 4; $i++) {
                [PSCustomObject]@{
                    Name  = "Name$i"
                    Date  = (Get-Date).ToString()
                }
            }
        } -ClickScriptBlock {
            if ($WebEvent.Data.Value -eq 'Name1') {
                Sync-PodeWebTable -Id 'DriveExplorer'
            }
            elseif ($WebEvent.Data.Value -eq 'Name2') {
                Move-PodeWebUrl -Url ($Request.UrlReferrer.ToString() + '?value=' + $WebEvent.Data.Value)
            }
            elseif ($WebEvent.Data.Value -eq 'Name3') {
                Show-PodeWebToast -Message $WebEvent.Data.Value
            }
        }
    )
}
```
