### ISSUE TITLE
Unexpected JSON from Set-PodeResponseAttachment

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode.Web#30]
If file is empty and downloading from Pode.Web button you get a JSON instead of the empty file.
```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Protocol Http
    # Set-PodeViewEngine -Type Pode
    Use-PodeWebTemplates -Title Tools

    Add-PodeStaticRoute -Path '/assets' -Source './assets' -DownloadOnly

    # GET request to download a file from static route
    Add-PodeRoute -Method Get -Path '/download' -ScriptBlock {
        Set-PodeResponseAttachment -Path '/assets/file.txt'
    }

    Add-PodeWebPage -Name 'Drive' -Icon Activity -Layouts @(
        New-PodeWebCard -Name 'Explorer' -Content @(
            New-PodeWebButton -Name 'Download' -Icon 'Download' -IconOnly -ScriptBlock {
                Set-PodeResponseAttachment -Path '/assets/file.txt'
            }
        )
    )
}
```
file filled with like `{}` or `{"Icon":"info","Message":"Download fdsfds","Title":"Message","ElementType":"Toast","Operation":"Show","Duration":3000}`

I think it's something in here in Pode.Web in here https://github.com/Badgerati/Pode.Web/blob/e327dfa9d89146fec06babb268bcabe0a9a5b1d0/src/Public/Elements.ps1#L1073

**Comment by Badgerati** [comment]
I've set it to check for the `Content-Disposition` header on the response, instead of the ContentLength.

**Comment by ili101** [comment]
LGTM 👍
