### ISSUE TITLE
implementation of the RBAC model 

### ISSUE THREAD

**Issue by behrouzamiri** [Badgerati/Pode.Web#303]
Dear @badgerati (Matthew),

is there a way to control what pages/areas are available to the authenticated user?
I need to know the right way about how's the best way to implement Role-Based Access Control, especially when using IIS as the Pode server host, and WindowsAd (AD Groups) as the Auth source within Pode/Pode.Web.

Your project already made a lot of dreams happen! you better know that! :hugs:

**Comment by Badgerati** [comment]
Hi @behrouzamiri,

Pages is likely the easiest to control, as `Add-PodeWebPage` has an `-AccessGroups` parameter. If you supply the group names to this parameter for the groups you wish to see the page, Pode.Web will restrict access for you, so long as `Add-PodeAuthWindowsAd` doesn't have `-NoGroups`.

```powershell
Add-PodeWebPage -Name 'Example' -AccessGroups 'devs' # Etc
```

Specific areas/layouts/elements is a little more involved, and I've made a note to look into how to make this easier. For specific areas within a Page you'd have to check `$WebEvent.Auth.User.Groups` contains the group that should have access manually:

```powershell
if ($WebEvent.Auth.User.Groups -icontains 'devs') {
    # show some container
}

# etc.
```

Hope that helps, and thank you! 😄

**Comment by behrouzamiri** [comment]
Thank you so much Matthew.

That's exactly what I was looking for. I was aware about the WebEvent workaround, and I think it makes sense to me if I want to control access to specific area within a page, that's the go!
However, most products are designed in such a way that menu/page-based implementation of RBAC (usually, a menu/page which is visible to me, but not to others with less privileges) is achieved. This is approach is more clear and even simpler for us while designing products.
That's why I was looking for it.
Thank you so much for the help.
I was sure the answer is not out there (I checked Docs and issues before asking) however, obviously I've missed that switch on the Function documentation, and I'm sorry for this.
🌹🌹🌹
What you've created so far, is incredible! That's Art, man.


________________________________
