### ISSUE TITLE
modal or equivalent

### ISSUE THREAD

**Issue by ThomasPerezBlanco** [Badgerati/Pode.Web#306]
Hello,

I use a form for the creation of an account.
When the 'submit' button is pressed, I would like to have a modal or other, to follow the progress of the account creation.
Do you know how I can do this?
I know how to create a modal, however, I would like the user to not be able to remove it until the creation has been completed.

Thanks for your help.

**Comment by Badgerati** [comment]
Hi @ThomasPerezBlanco,

In the modal you have, are you able to follow progress at the moment? and it's just that the user could, if they wanted to, close the modal prematurely?

Would the ability to disable the closing of the modal by the user, until the account has been created, work? Because I might be able to do something there using output actions 🤔

**Comment by ThomasPerezBlanco** [comment]
Hi,

Sorry for the late reply, shame on me.

Yes, I can track the progress, what I wanted was to block the user from closing the modal until processing was complete.

I managed to do what I want with JavaScript code, for example:

document.getElementById('newComersForms').addEventListener('submit', function(evt){
    $("#newComersModal").modal({
       backdrop: "static"
     });
})

It would be nice to have some extra options for the modal in the module, so you don't have to type in JavaScript.

Thank you 👍

**Comment by eugen257** [comment]
@Badgerati,

I have many questions if I may. your creation is so versatile and unique. I like.

Modal question - is it possible to show a window with only one button ' closed' ?

Thanks you

**Comment by Badgerati** [comment]
Hi @eugen257,

I'm guessing the modal you're displaying has ` -ScriptBlock` defined? Currently the "submit" is only hidden if there's no scriptblock, so it'll have to be a new parameter that needs to be added.

**Comment by ThomasPerezBlanco** [comment]
Sorry, I forgot to close.
