### ISSUE TITLE
Question : horizontally scrollable table

### ISSUE THREAD

**Issue by phende** [Badgerati/Pode.Web#316]
I understand from Bootstrap documentation that a table within a `<div class="table-responsive">` should be horizontally scrollable, but I can't get Pode.Web tables to become scrollable although they are already enclosed in that exact div.

Being a noob at HTML and Bootstrap I am probably missing something obvious, but I would be grateful if you could point me to the right direction.

By the way, I love Pode.Web, thanks for your work.

**Comment by Badgerati** [comment]
Off the top of my head, I'm not too sure.

When I get chance, I'll have a look; though I've a feeling there could be a parent div overriding the x-overflow to hide it 🤔

**Comment by Badgerati** [comment]
Another user in Discord had the same question, and got it working via `-CssStyle`. Be interesting to see if it's possible to have this in Pode.Web built in:

```powershell
New-PodeWebTable -CssStyle @{'display'='block';'overflow-x'='auto';'white-space'= 'nowrap'}
```

**Comment by phende** [comment]
Excellent, that worked like a charm! Many thanks to you and to the Discord contributor.
