### ISSUE TITLE
Passing variables into another component

### ISSUE THREAD

**Issue by ThomasPerezBlanco** [Badgerati/Pode.Web#318]
Hello,

I hope that you all are ok.

I want to pass variables from a form to another component.
In summary, I want a user to be able to query an Active Directory account and display the desired information.

example :

![image](https://user-images.githubusercontent.com/44971529/175654752-c62d8cb9-37e3-4d95-ab2c-ce4516ba1f2f.png)

I don't know how to pass the form variables to another component...

My second component is a : New-PodeWebRaw.
example :

![image](https://user-images.githubusercontent.com/44971529/175655274-eb879aaf-4f9b-49f6-a568-dcf666447655.png)

Do you know how can I do?

Thanks.

Cordially,

Thomas.

**Comment by ThomasPerezBlanco** [comment]
Hello,

After many tries, I succeeded by doing this:

![image](https://user-images.githubusercontent.com/44971529/175776648-24f98710-6e86-4fec-98f6-bf1fd07fe57f.png)

On the other hand, I find that ugly.
A good idea would be to inject parameters to the 'New-PodeWebRaw' command and be able to update it.

Cordially,

Thomas.

**Comment by ThomasPerezBlanco** [comment]
Hi @Badgerati,

First of all, thank you for your excellent work.
Super idea the command Update-PodeWebComponentValue [-Id].
Yes, putting the header on the 1st column is very good for visualization on an object, it can be useful for many users.

Thank you.

**Comment by phende** [comment]
Hi @ThomasPerezBlanco, here is how I do the table thing:

Add a little CSS to a file imported using Import-PodeWebStylesheet:
```
.noheadertable thead {
    display: none;
}
```

Then:
```
New-PodeWebTable -Name 'DetailsTable' -CssClass 'noheadertable' -CssStyle @{ width = 'auto' } -Compact -NoRefresh -NoExport -ScriptBlock {
    $Data = Fetch-SomeData

    # Optional, just to make some labels more user friendly
    $Translations = @{
        BatchTime = 'Migration time'
        ApplicationCustodian = 'Application custodian'
        InfrastructureCustodian = 'Infrastructure custodian'
        Datacenter = 'vSphere datacenter'
        Cluster = 'vSphere cluster'
        ProcessControl = 'Process control'
        OS = 'Operating system'
        CloudLocation = 'Cloud location'
    }
    
    # List of $Data properties to display
    @('Name', 'Datacenter', 'Cluster', 'Class', 'Category', 'Status', 'ApplicationCustodian','InfrastructureCustodian',
        'Escalation', 'Criticality', 'ProcessControl', 'Restricted', 'Production', 'Usage', 'OS', 'Group', 'Wave', 'Batch',
        'BatchTime', 'CloudLocation', 'Comment', 'Manager', 'Organization') | ForEach-Object {
        [Ordered]@{
            Key = $Translations[$_] ? $Translations[$_] : $_
            Value = $Data.$_
        }
    }

    # Optionally, add some extra properties that are formatted differently
    $Data.IP -split ',' | ForEach-Object {
        [Ordered]@{
            Key = 'IP address'
            Value = $_
        }
    }
    $Data.Portgroups | ForEach-Object {
        [Ordered]@{
            Key = 'Portgroup'
            Value = $_
        }
    }
} -Columns @(
    Initialize-PodeWebTableColumn -Key Value -Default ''
)
```

The Update-PodeWebComponentValue would indeed be very nice to have.

**Comment by ThomasPerezBlanco** [comment]
Sorry, I forgot to close.
