### ISSUE TITLE
Add-PodeWebPage Group support with spaces

### ISSUE THREAD

**Issue by phdavis** [Badgerati/Pode.Web#323]
Add-PodeWebPage Group names with spaces in them do not expand. I tried to URLEncode the group name and it added a + to the name but still didnt fix the issue completely. I suspect there's more to it 😃 

`Add-PodeWebPage -Name 'Page Name 1' -Group 'Spaced Name' -Icon 'Settings' -ScriptBlock {}`

<img width="322" alt="image" src="https://user-images.githubusercontent.com/16641704/179862164-aba30002-39f3-4d6a-a774-a95afa521ca8.png">

Removing the space works fine.
`Add-PodeWebPage -Name 'Page Name 1' -Group 'SpacedName' -Icon 'Settings' -ScriptBlock {}`

<img width="328" alt="image" src="https://user-images.githubusercontent.com/16641704/179861980-51d32a77-dbb3-49df-a6bd-0f1b3cadc846.png">

**Comment by Badgerati** [comment]
Hey @phdavis,

This will be the same as #255 😃 the HTML properties that do the selection also contain the space, which breaks the javascript behind the scenes.
