### ISSUE TITLE
Add RequiredModules section to the module manifest

### ISSUE THREAD

**Issue by IvanDrag0** [Badgerati/Pode.Web#333]
Since Pode.Web cannot run without the Pode module installed, a `RequiredModules` section referencing the Pode module should be added to the Pode.Web module manifest.

For example:

`RequiredModules = 'Pode'`

Or if a specific version is required:

`RequiredModules = @{ModuleName="Pode";GUID="e3ea217c-fc3d-406b-95d5-4304ab06c6af";ModuleVersion="2.7.1"}`

**Comment by Badgerati** [comment]
I often forget `RequiredModules` is a thing! It should also mean I can remove the logic that does the module checking 🤔

**Comment by IvanDrag0** [comment]
@Badgerati I would definitely do that and let Powershell do the checking and resolution. Also since it means less coding and testing for you :)

**Comment by kprocyszyn** [comment]
I could actually try to implement this - at some point I've managed to have PowerShell to install all required modules in case they were not installed. Although I had this going with private nuget feed, I'm pretty certain I could do it with public gallery.

Let me know.

**Comment by Badgerati** [comment]
@kprocyszyn just saw your message here, sorry! I've just added a commit for using RequiredModules :)
