### ISSUE TITLE
Password string

### ISSUE THREAD

**Issue by eugen257** [Badgerati/Pode.Web#337]
Hi,

is there any way to add a "show/hide password" button to the "New-PodeWebTextbox -Type Password" or "New-PodeWebCredential -Type Password".

I'm sorry I didn't find how.

Thank you

**Comment by Badgerati** [comment]
Hi @eugen257,

There isn't at the moment, it'll label as a feature to be implemented :)

**Comment by eugen257** [comment]
Packed in a Container. Topic Closed
Thanks
