### ISSUE TITLE
Find the Error

### ISSUE THREAD

**Issue by eugen257** [Badgerati/Pode.Web#338]
Hi,

how can i find the error in the code? how to understand what "Value" is wrong?
Thanks

> Date: 2022-08-24 16:18:04
Level: Error
ThreadId: 1
Server: 
Category: InvalidData: (:) [Invoke-PodeScriptBlock], ParameterBindingValidationException
Message: Das Argument kann nicht an den Parameter "Value" gebunden werden, da es NULL ist.
StackTrace: bei <ScriptBlock>, <Keine Datei>: Zeile 83
bei Invoke-PodeScriptBlock, C:\Program Files\WindowsPowerShell\Modules\Pode\2.7.1\Public\Utilities.ps1: Zeile 642
bei <ScriptBlock>, <Keine Datei>: Zeile 7
bei Invoke-PodeScriptBlock, C:\Program Files\WindowsPowerShell\Modules\Pode\2.7.1\Public\Utilities.ps1: Zeile 634
bei <ScriptBlock>, <Keine Datei>: Zeile 106

> Date: 2022-08-24 16:18:04
Level: Error
ThreadId: 1
Server: 
Category: System.Management.Automation
Message: Das Argument kann nicht an den Parameter "Value" gebunden werden, da es NULL ist.
StackTrace:    bei System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   bei Invoke-PodeScriptBlock(Closure , FunctionContext )
   bei System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   bei System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   bei System.Management.Automation.CommandProcessorBase.Complete()

**Comment by Badgerati** [comment]
Yeeeah, when the error shown is at `Invoke-PodeScriptBlock`, it's actually a function within the scriptblock it's invoking. When this happens, it's a pain unless you know roughly which area of the code might be causing the error.

Usually it should show the actual function, so this is a bit weird 🤔 

Have you got any ideas as to where in your server this error might be coming from? What you're doing at the time the error is written, such as loading a page, submitting a form, etc., those will help.

Or if it's possible, maybe give an example of your server here?

**Comment by eugen257** [comment]
Hi @Badgerati,

i found an error. It is certainly difficult to search if it is not explicitly shown. But the mistake was that I changed the ID of the element in only one place and then forgot. Everything is fine. I myself am to blame. Thank you.

**Comment by eugen257** [comment]
this also happens if `New-PodeWebBadge -Value '' ` is empty. The error is also unknown and you need to look for it yourself.
