### ISSUE TITLE
Add Discussions section to the repo

### ISSUE THREAD

**Issue by IvanDrag0** [Badgerati/Pode.Web#341]
A [Discussions](https://docs.github.com/en/discussions) section should be added to the repo (as well as the main Pode repo) so that users can ask questions and discuss things without generating a bunch of issues.

**Comment by Badgerati** [comment]
Aaah, I thought Pode.Web had it enabled, I'll do that when I get chance!

Pode already has it enabled :)

**Comment by Badgerati** [comment]
Now enabled in Pode.Web :)
