### ISSUE TITLE
[style guidance] Please add workspace settings for VSCode

### ISSUE THREAD

**Issue by thekamilpro** [Badgerati/Pode.Web#343]
I take it you write your code in VS Code...

There's great feature in VS Code called Workspace settings: https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings

In this you can overwrite user's settings just for the given workspace (or in this case, GitHub repo), without making any changes to my actual settings of VS Code.

E.g. my PowerShell extension is configured to open scriptblock brackets in the new line, while all code I can see here opens scriptblock brackets in the  same line - so when I right click and press format, it rearranges whole file.

It's nothing major really, but nice to have, and effort to implement it is minimal.

**Comment by Badgerati** [comment]
Completed via #536 😄
