### ISSUE TITLE
The Script stops

### ISSUE THREAD

**Issue by eugen257** [Badgerati/Pode.Web#352]
example:
I want to create a group in activedirectory, and if it already exists with the same name, then the script doesn't go any further. Checking if there is already a group or not also stops executed scripts

-------------------------------------------
Date: 2022-09-16 17:10:44
Level: Error
ThreadId: 1
Server: voip-server
Category: NotSpecified: (CN=....:String) [New-ADGroup], ADException
Message: Die angegebene Gruppe ist bereits vorhanden
StackTrace: bei <ScriptBlock>, <Keine Datei>: Zeile 414
bei <ScriptBlock>, <Keine Datei>: Zeile 376
bei Invoke-PodeScriptBlock, C:\Program Files\WindowsPowerShell\Modules\Pode\2.7.1\Public\Utilities.ps1: Zeile 642
bei <ScriptBlock>, <Keine Datei>: Zeile 6
bei Invoke-PodeScriptBlock, C:\Program Files\WindowsPowerShell\Modules\Pode\2.7.1\Public\Utilities.ps1: Zeile 634
bei <ScriptBlock>, <Keine Datei>: Zeile 106

Date: 2022-09-16 17:10:44
Level: Error
ThreadId: 1
Server: 
Category: Microsoft.ActiveDirectory.Management
Message: Die angegebene Gruppe ist bereits vorhanden
StackTrace:    bei Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForExtendedError(String extendedErrorMessage, Exception innerException)
   bei Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForErrorCode(String message, String errorCode, String extendedErrorMessage, Exception innerException)
   bei Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowExceptionForFaultDetail(FaultDetail faultDetail, FaultException faultException)
   bei Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowException(AdwsFault adwsFault, FaultException faultException)
   bei Microsoft.ActiveDirectory.Management.AdwsConnection.Create(ADAddRequest request)
   bei Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADSyncOperations.Add(ADSessionHandle handle, ADAddRequest request)
   bei Microsoft.ActiveDirectory.Management.ADActiveObject.Create()
   bei Microsoft.ActiveDirectory.Management.Commands.ADNewCmdletBase`3.ADNewCmdletBaseProcessCSRoutine()
   bei Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
   bei Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.ProcessRecord()

Date: 2022-09-16 17:10:44
Level: Error
ThreadId: 1
Server: 
Category: 
Message: Der bereitgestellte Eintrag ist bereits vorhanden.
StackTrace:

**Comment by Badgerati** [comment]
Hi @eugen257,

Is the issue that you want the script to stop and it doesn't, or that the AD commands stop the script? Do you have an example of the script that's being run?

If it's that the AD commands are erroring, does adding `-ErrorAction Ignore` to them resolve the issue?

**Comment by eugen257** [comment]
Hi @Badgerati,

unfortunately also:

![image](https://user-images.githubusercontent.com/111352399/191981273-4de193fc-870d-4e31-9178-1741a8bce33b.png)

For example, I create an ad-group. here I can either check whether it already exists or create it without checking.
If the group already exists, then when checking and without it, it freezes like this, although the script creates everything, but does not return any data to the web form.

**Comment by Badgerati** [comment]
Hi @eugen257,

Are you able to provide an example of the page, form, and script code for me to look over?

**Comment by Badgerati** [comment]
Hi @eugen257,

Doing some quick Googling, it looks like `-ErrorAction` on the AD cmdlets doesn't work. According to https://stackoverflow.com/a/6309186, wrapping a `Get-ADGroup` in a `try {} catch {}` and then doing the `New-ADGroup` in the catch block should work.

**Comment by eugen257** [comment]
Thanks @Badgerati
