### ISSUE TITLE
Send Email

### ISSUE THREAD

**Issue by eugen257** [Badgerati/Pode.Web#353]
Hi all,

I will be grateful for your help.

I can't send email, I get the error:

WARNING: The command 'Send-MailMessage' is obsolete. This cmdlet does not guarantee secure connections to SMTP servers. While there is no immediate replacement available in PowerShell, we recommend you do not use Send-MailMessage at this time. See https://aka.ms/SendMailMessage for more information.

**Comment by Badgerati** [comment]
Hi @eugen257,

I believe you now have to use the `MailMessage` object in PowerShell to send emails: https://stackoverflow.com/a/61168324
