### ISSUE TITLE
Feature request: Navbar

### ISSUE THREAD

**Issue by datenschieber** [Badgerati/Pode.Web#36]
Please add support for the Navbar component of Bootstrap [https://getbootstrap.com/docs/4.6/components/navbar/](url)

**Comment by Badgerati** [comment]
Hey @datenschieber,

Pode.Web already uses the navbar, so I'm guessing you want support to be able to add buttons/links to the navbar, or as a sub-navbar beneath the main one?

**Comment by datenschieber** [comment]
Hi @Badgerati,

yes, exactly. A navbar at the top like the classic menu bar in desktop applications and as shown in the Bootstrap docs. Perfect would be support for dropdowns.

**Comment by Badgerati** [comment]
Added in support to add links, and dropdowns, to the top navbar. With the above commit, doing the following:

```powershell
$link1 = New-PodeWebNavLink -Name 'Home' -Url '/' -Icon Home

$link2 = New-PodeWebNavLink -Name 'Dynamic' -Icon Settings -NoAuth -ScriptBlock {
    Show-PodeWebToast -Message "I'm from a nav link!"
}

$div1 = New-PodeWebNavDivider

$link3 = New-PodeWebNavLink -Name 'Disabled' -Url '/' -Disabled

$dd1 = New-PodeWebNavDropdown -Name 'Dropdown' -Icon 'maximize-2' -Items @(
    New-PodeWebNavLink -Name 'Twitter' -Url 'https://twitter.com'
    New-PodeWebNavLink -Name 'Facebook' -Url 'https://facebook.com' -Disabled

    New-PodeWebNavDivider

    New-PodeWebNavDropdown -Name 'InnerDrop' -Items @(
        New-PodeWebNavLink -Name 'Twitch' -Url 'https://twitch.tv'
        New-PodeWebNavLink -Name 'Pode' -Url 'https://github.com/Badgerati/Pode'
    )
)

Set-PodeWebNavDefault -Items $link1, $link2, $div1, $link3, $dd1
```

Will look like this:
![image](https://user-images.githubusercontent.com/1483395/113902281-9cce8b80-97c7-11eb-8e42-b0165bb3456d.png)

**Comment by datenschieber** [comment]
Hi @Badgerati,

just perfect! Very pragmatically and straight forward solution! Thanks!
