### ISSUE TITLE
[i18n] -Name argument not support Chinese

### ISSUE THREAD

**Issue by lost22git** [Badgerati/Pode.Web#361]
-Name argument not support Chinese now or add new argument like -Title to support Chinese ?

**Comment by Badgerati** [comment]
Hi @lost22git,

Have you got an example of the function you're trying to use? `-Name` makes sense since it's also used for `-Id` if not supplied, but most functions have a `-DisplayName` that should be alright.

**Comment by lost22git** [comment]
@Badgerati 

* Both `New-PodeWebChart`  and ` New-PodeWebTable` do not have  arguments `-DisplayName`  or `-Title`.

* Even if `Add-PodeWebPage` set `-Name Processes -Title 进程`, the title of sidebar is still `Processes`  

![image](https://user-images.githubusercontent.com/65008815/197641390-6d7b99c9-6c9b-49dd-a4bf-a7ac45e031c9.png)
