### ISSUE TITLE
PodeWebContainer resize

### ISSUE THREAD

**Issue by eugen257** [Badgerati/Pode.Web#363]
Hi,

is it possible to resize New-PodeWebContainer ?

for example 😊:

![image](https://user-images.githubusercontent.com/111352399/195909935-f90fe16e-e83c-493f-87d1-75b9dc4bab52.png)

**Comment by jbaechtelMT** [comment]
Not sure about what you mean, resize Container?  What your example appears to show is Containers inside of Grid Cells?  What you tried that?

**Comment by eugen257** [comment]
Hi @jbaechtelMT,

The PodeWebContainer has a standard size and stretches to the full length of the page. I mean change the size of the container, for example, make them two, three in a row so that you can display brief information there. Is it possible? or can it only be done by changing the css ?
Thanks

**Comment by jbaechtelMT** [comment]
The following example should create a single Container (the entire page) and then creates a Grid of Cells (3 across) inside of that Container.  Then inside each of the Cells, it creates Containers (left, middle, right) in each of those Cells.  Then inside each of those Containers, Text is displayed.  Hope it Helps:

New-PodeWebContainer -Content @(                       # Outer Page Container
     New-PodeWebGrid -Cells @(
          New-PodeWebCell -Content @(                  # Left Grid Cell
               New-PodeWebContainer -Content @(        # Left COntainer
                    New-PodeWebText -Name 'LeftCellContainerText' -Value "Left Cell Container Text"
               )
		)
          New-PodeWebCell -Content @(                  # Middle Grid Cell
               New-PodeWebContainer -Content @(        # Middle Container
                    New-PodeWebText -Name 'MiddleCellContainerText' -Value "Middle Cell Container Text"
               )
          )
          New-PodeWebCell -Content @(                  # Right Grid Cell
               New-PodeWebContainer -Content @(        # Right Container
                    New-PodeWebText -Name 'RightCellContainerText' -Value "Right Cell Container Text"
               )
          )
     )
)

**Comment by eugen257** [comment]
@jbaechtelMT,

thank you so much, everything is amazing. **Thanks** 👍👍👍
