### ISSUE TITLE
$state: not working in pages / dot-sourced files (Get-PodeState works)

### ISSUE THREAD

**Issue by jsg91** [Badgerati/Pode.Web#372]
Below doesn't work, while doing same with Get-Podestate in pages/statetest.ps1 works
Server.ps1:
```
Import-Module Pode.Web
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http
    Use-PodeWebTemplates -Title 'Statetest' -Theme Dark
	$state:test = "Hello"
	Use-PodeWebpages
}
```
pages/statetest.ps1:
```
Add-PodeWebPage -Name 'StatetestPage' -ScriptBlock {
	New-PodeWebForm -Name 'Form' -ScriptBlock {
	} -Content @(
		New-PodeWebRaw $state:test
		#New-PodeWebRaw (Get-PodeState test)
	)
}
```

**Comment by Badgerati** [comment]
Hi @jsg91,

This is expected for now, it's a similar issue as to why `$using:` also doesn't work and will be covered by #138.

In Pode.Web using `Get-PodeState` is the way to go until support is added for `$state:`.
