### ISSUE TITLE
Unicode Menu

### ISSUE THREAD

**Issue by eugen257** [Badgerati/Pode.Web#384]
### Describe the Bug
Unicode problems.
in the previous version, everything showed fine, but since the latest version, only in the text of the menu began to show such a place of characters "ü ä ö".

### Screenshots
![image](https://user-images.githubusercontent.com/111352399/207319607-f3716abf-cbac-4ac8-956f-d2ee5efc8c11.png)

### Platform
 - OS: [Windows 10]
 - Browser: [*]
 - Versions:
   - Pode.Web: [e.g. Pode.Web v0.8.2]
   - PowerShell: [e.g. PS7.2.7]

**Comment by ili101** [comment]
Also on `Out-PodeWebValidation` `"` is encoded. example from here https://github.com/Badgerati/Pode.Web/issues/390
![image](https://user-images.githubusercontent.com/6960531/209588037-db3aed6d-f858-4a3f-bebb-3e47c31460a7.png)

**Comment by eugen257** [comment]
Hallo @ili101,

this is not suitable, because It's not a text box, it's the title of the page.
`Add-PodeWebPage -Name 'Kennwort zurücksetzen'` - this element displays the wrong encoding ('ü')
