### ISSUE TITLE
HTMX Support via Custom Attributes

### ISSUE THREAD

**Issue by fatherofinvention** [Badgerati/Pode.Web#393]
### Describe the Change
I would like to request an enhancement to the Pode.Web PowerShell module so that it supports using HTMX via custom data attributes.

### Additional Context
HTMX is a powerful technology for building web applications that allows for real-time updates to the page without requiring a full page refresh. It can significantly improve the user experience and performance of web applications. By supporting HTMX via custom data attributes in the Pode.Web PowerShell module, users will be able to more easily build web applications that leverage this technology in their PowerShell scripts.

Refer to: https://htmx.org/docs/#introduction

This could be a potent boost in functionality if supported.

**Comment by Badgerati** [comment]
Hi @fatherofinvention,

Now that looking interesting! I've been toying with the idea of using React but it'll take a lot of time for me to learn and overhaul Pode to use it. This looks like it could be more lightweight and possibly simpler 🤔 

I'll look into it more, thanks!

**Comment by fatherofinvention** [comment]
Hey @Badgerati , you’re welcome! You’ve done an amazing job on Pode. The level of engineering and attention to detail is impressive and I’m having such a good time learning how to use it. Please keep it up :)

Thanks for considering this request, I hope it works out!

**Comment by fatherofinvention** [comment]
@Badgerati - Just re-opening this briefly to ask a question. It seems to me I could actually make use of HTMX in Pode using [Views](https://badgerati.github.io/Pode/Tutorials/Views/Pode/), right? Since I can include Javascript and write my own HTML it seems like it would work. Am I understanding that correctly? TY!
