### ISSUE TITLE
Update-PodeWebLink ?

### ISSUE THREAD

**Issue by eugen257** [Badgerati/Pode.Web#394]
### Question

Update-PodeWebRaw is no.
Update-PodeWebLink is no.
New-PodeWebText doesn't support links.

How can I update/show the generated link?

Thanks

**Comment by Badgerati** [comment]
Hi @eugen257,

I was about to suggest `Update-PodeWebText` might work, but for some reason I appear to have not tagged it with the `pode-text` class 😱 

So currently, it's not possible and will need fixing. `Update-PodeWebRaw` is something that's been asked for in the past as well 👍
