### ISSUE TITLE
Clearing Out-PodeWebTextbox

### ISSUE THREAD

**Issue by fatherofinvention** [Badgerati/Pode.Web#395]
### Question
I see that `Out-PodeWebTextbox` doesn't have a `-Name` parameter, so I am wondering how I can clear its contents with a reset button? I thought maybe `Clear-PodeWebTextbox` but it seems that is only intended for `New-PodeWebTextbox`. I'm sure there is something I'm missing here. Appreciate the help!

**Comment by Badgerati** [comment]
The idea behind `Out-PodeWebTable`, `Out-PodeWebChart` and `Out-PodeWebTextbox` originally was just to quickly output the result of some script to an adhoc table/chart/textbox. If you `Out-` from the same form/etc it should re-render the adhoc control.

The `Out-`'d elements should have an ID though, for a textbox it should be `txt_` plus the "sender's" ID. So if a Form created the Textbox, and the Form had an ID of "search_form", the Textbox would be "txt_search_form". If you right-click the textbox and select "Inspect Element", it should show in the Dev Console :)

All of the others outputs actions are for the main elements, but I don't see any reason to not add a Name/Id parameters for the `Out-`'d elements as well!

**Comment by fatherofinvention** [comment]
Awesome, thank you @Badgerati !

**Comment by Badgerati** [comment]
So a lot has changed now for the Pode.Web v1.0 release!

With #455 now merged all of the `Out-` actions have been removed, and you can now use all of the `New-` functions in their place. Meaning `Clear-PodeWebTextbox` will work as expected 😃 

I'll close this issue.
