### ISSUE TITLE
Cannot create table with file view

### ISSUE THREAD

**Issue by hrebynakha** [Badgerati/Pode.Web#398]
Hi.
I want to create a simple directory browsing using New-PodeWebTable and Get-ChildItem
but table with this function not working :(

For example, show the list of files in C:\Windows folder

``` 
Import-Module -Name Pode.Web
Start-PodeServer  {
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging

    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http -Name 'Test'
    Use-PodeWebTemplates -Title 'Powershell Test Pode' -Theme Dark
    Add-PodeWebPage -Name 'File' -Icon 'file-cog' -ScriptBlock {
        $files = Get-ChildItem -Path "C:\Windows" -File | Select-Object *
        New-PodeWebList -Values $files.Name -Numbered
        New-PodeWebList -Values $files.FullName -Numbered
        New-PodeWebTable -Name 'Files' -ScriptBlock {
            foreach ($file in ($files)) {
                [ordered]@{
                    Name = "$($file.Name)"
                    FullName = "$($file.FullName)"
                }
            }
        }
    }
}
```

File object received and shown by  **New-PodeWebList**  function but table not show any item :(

### Platform
 - OS: Windows
 - Browser:  Chrome 
 - Versions:
   - Pode: 2.7.1
   - Pode.Web: 0.8.1
   - PowerShell:    5.1.19041.1682

**Comment by kort3x** [comment]
I think it's an scoping issue: $files is empty in the Scriptblock of New-PodeWebTable.

Try passing $files to the -ArgumentsList paramter of New-PodeWebTable.

**Comment by hrebynakha** [comment]
Yes. You right. $files  is empty , but using -ArgumentsList does not give result.  I just move this block ```$files = Get-ChildItem -Path "C:\Windows" -File | Select-Object *``` to inside of **New-PodeWebTable**

> I think it's an scoping issue: $files is empty in the Scriptblock of New-PodeWebTable.
> 
> Try passing $files to the -ArgumentsList paramter of New-PodeWebTable.
