### ISSUE TITLE
Updating Page Values Without Restarting Server

### ISSUE THREAD

**Issue by fatherofinvention** [Badgerati/Pode.Web#400]
### Question
How can I update the values on a webpage without restarting the server? Currently, I am checking if a module is installed and displaying the version if it is using `New-PodeWebText -Value "Module version: $modVer"`. If the module is not installed, I display a button that, when clicked, installs the module. After the module is installed, I want to update the text elements on the page to check for the version again. However, I have not been able to do this without restarting the server. Is there a way to re-evaluate the logic for a specific script block on an element, or the entire page without restarting the server?

**Comment by ili101** [comment]
Like this?
https://badgerati.github.io/Pode.Web/Tutorials/Outputs/Text/#update

**Comment by fatherofinvention** [comment]
Wow, no clue how I missed that LOL. Yes, like that. Thanks @ili101.

Is there anyway to re-evaluate the logic for the entire page without restarting Pode?

**Comment by ili101** [comment]
Use `Add-PodeWebPage` `-ScriptBlock {}` instead or in addition to `-Layouts`
https://badgerati.github.io/Pode.Web/Tutorials/Pages/#dynamic

**Comment by fatherofinvention** [comment]
Cool, thank you @ili101
