### ISSUE TITLE
Dynamic Form with more than one output 

### ISSUE THREAD

**Issue by idanmashaal** [Badgerati/Pode.Web#404]
Hi, @Badgerati !
I have a dynamic form (using -ScriptBlock) based on the process example in your examples repo. When entering a process name, for example ‘pwsh’ it provides the output as expected.  

Im trying to add to the output a web link (HREF) based on the form input data for example https://127.0.0.1/somethingElse?name=pwsh

But I’m not able to make this happen using Pode.Web — meaning I’m not sure what to do. 

Using standard Pode with view templates allow me to customize the HTML and this works as expected. 

Would appreciate your guidance,
Thanks,
Idan.

**Comment by Badgerati** [comment]
Hi @idanmashaal,

I think I know what you mean: is it that you're trying to add a link as a new column within the table that outputted from the `processes.ps1` example?

**Comment by idanmashaal** [comment]
Hi @Badgerati ,

Let me share some screenshots of the example form I made.
It's based on the Processes example.
The form has a "Debug" button that provides the output in JSON (just for simplicity). If it's not Debug it is shown text as is.

Debug unchedked:
![image](https://user-images.githubusercontent.com/377019/211518336-6395793f-2c70-4ed6-86a4-75355471b2c2.png)

Debug checked:
![image](https://user-images.githubusercontent.com/377019/211518437-5dc7f16d-a5e8-4162-a494-88bf7e717534.png)

What I would like is that when debug is checked, below the text box output, there will also be a button or hyperlink that will resolve to a url that has the input or any other value from the output in it. For example: /something?pname=pwsh or /something?pid=24339

Hope this is clearer now with the screenshots :)

Thanks,
Idan.

**Comment by Badgerati** [comment]
In Pode.Web v1.0.0-preview1 this is now achievable, as v1.0.0 allows you to render new elements on the fly from the server, and asynchronously as well :)

Docs: https://badgerati.github.io/Pode.Web/1.0.0/Tutorials/Actions/Elements/#out
