### ISSUE TITLE
Simultaneous actions from the same user with sessions enabeled

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode.Web#406]
### Describe the Feature
I made a tool with multiple steps, after some time I started to get errors, turned out users started to run multiple Tabs of the tool and work in parallel to save time and this caused conflicts in the user `$WebEvent.Session.Data`.

### Solution 1
The solution I implemented for now is to create a global PodeLockable that hold objects that tracks if the same session id is trying to execute simultaneously and will throw.
Users that want to run simultaneously can use "Firefox Multi-Account Containers" or "SessionBox - Multi login to any website".

Are there better ways to do this?
When you login to sites like github/twitter your session is shared for all your tabs and survives a browser restart.
Contrary to this sites like banks and some tools use a local session to the tab.
I see that in order to distinguish between different tab you can use some client side solutions https://stackoverflow.com/questions/368653/how-to-differ-sessions-in-browser-tabs

some options I can think of:
### Option 2
Something like `Enable-PodeSessionMiddleware -PerTab`
This option will replace the session id whit a per tab one. every tab will be independent. 
### Option 3
Something like `Enable-PodeSessionMiddleware -PerTab`
This option will alternatively add another item like `$WebEvent.SessionTab`. You will be able to login once using  `$WebEvent.Session` and save the other data separately in `$WebEvent.SessionTab`. 
### Option 4
Use something like  `New-PodeWebTab` instead of actual tabs.
### Option 5
No need for any new session id, add hidden identification to the form
```powershell
    Add-PodeWebPage -Name 'Page1' -Icon 'cart-minus' -ScriptBlock {
        $Guid = New-Guid
        New-PodeWebAccordion -Bellows @(
            New-PodeWebBellow -Name 'wizard' -Content @(
                New-PodeWebSteps -Name "Steps" -Steps @(
                    New-PodeWebStep -Name "Step1" -Icon 'cog-outline' -Content @(
                        New-PodeWebHidden -Name 'csrf' -Value $Guid
                    ...
                    New-PodeWebStep -Name "Step2" -Icon 'cog-outline' -Content @(
                        New-PodeWebHidden -Name 'csrf' -Value $Guid
                    ...
```
refreshing the page or creating a new tab will have a new identification.

### question
Do you have some input/recommendation?
Options 4 and 5 can probably be implemented without new session id feature, but I think `$WebEvent.Session.Data` is not thread safe like PodeLockable so I will still have problems?

**Comment by Badgerati** [comment]
Hey @ili101,

This is an interesting suggestion, and from doing some further searching for other ideas they all pretty much centralise around one solution: `window.sessionStorage` (ie: the link given by yourself above, and [here](https://stackoverflow.com/questions/11896160/any-way-to-identify-browser-tab-in-javascript)). This comes with its own risks around XSS, but this wouldn't be the default session management and at the user's choice - so a warning in the docs should suffice.

Given this, Option 2 or 3 would be best to implement this properly within Pode. We can upgrade Pode to deal with the server side splitting of sessions, and then Pode.Web the client side with sessionStorage. Looking at the links it would appear to lean more towards Option 3; so every Tab would share the same server side Pode session, but the data would be split by a TabId in client side sessionStorage which we can pass through on each request to the server.

Out of interest, what/were there any errors being thrown for the `$WebEvent.Session.Data` conflicts? What data is it you're storing in the sessions that would cause the conflicts? Is it data that needs to be in the session?

**Comment by ili101** [comment]
Hi @Badgerati 
I started by writing the flows first as a linear CLI tools and then added Pode so maybe it's not optimized well for web. I do something like:
Step1 - Get subscription ID from user, get and validate subscription IDs and info from several APIs, reset the flow and save it: `$WebEvent.Session.Data.flow1= @{ Subscription = [Subscription]}`
Step2/3/4/etc - Get choices from user, get and validate more stuff like `$WebEvent.Session.Data.flow1.Plan = [Plan]`, `$WebEvent.Session.Data.flow1.Preference1= "Transition Option 1"` (steps are using info collected in previous steps).
Final Step - Execute the action using the saved objects info and the validated preferences selected.

Now with one tab there is no problem going back a step. or going back to step 1 midway starting over abandoning the incomplete flow.
But multiple tabs resoles in problems as for example tab 2 will reset tab 1 flow1 object or worst make a mismatch of subscription, plan and preferences objects etc.

Some of the steps can take up to 2 minutes as some of the APIs can be painfully slow (like Microsoft Partner Center). Submit stage can take somewhere from 2 to 20 minutes depending on how slow it's that day.
Is it better to move away from sessions to store everything in a shared state instead? indexed with some ID like in "Option 5"?
Optionally also moving the last submit stage to a task and make a tasks progress status page (although it won't solve any of the mentioned problems but feel cleaner).
