### ISSUE TITLE
Update-PodeTextBox should Update also PodeTextBox with -Type Date

### ISSUE THREAD

**Issue by frocentus** [Badgerati/Pode.Web#413]
### Describe the Bug
I want to set values on Text-Input-Elements of type 'Date'. The commandlet `Update-PodeWebTextbox` seems able to update elements created with `New-PodeWebTextBox` with `-Type Text` but not with `-Type Date` neither it can update elements created with `New-PodeWebDateTime`c

### Steps To Reproduce
I created a small Application showing this beahviour:
```
Import-Module -Name Pode.Web

Start-PodeServer {
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging 
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http
    Use-PodeWebTemplates -Title 'Formthing' -Theme Light

    $modal = New-PodeWebModal -Name 'TestModal' -Id 'date_modal' -AsForm -Content @(
        New-PodeWebTextBox -Name 'Date1' -DisplayName 'Textbox with no Type'
        New-PodeWebTextBox -Name 'Date2' -DisplayName 'Textbox with Type Date' -Type Date
        New-PodeWebDateTime -Name 'Date3' -DisplayName 'DateTime with Type Date' -Type Date
    )  -ScriptBlock {
        $WebEvent.Data | Out-Default
        Hide-PodeWebModal -Name 'TestModal'
    }

    $card = New-PodeWebCard -Name 'Testcard' -DisplayName "Test" -Content @(
        New-PodeWebButton -Name 'ShowModal' -DisplayName 'Show me that Modal ...' -Icon 'account-plus' -ScriptBlock {
            Show-PodeWebModal -Id 'date_modal' -Actions @(
                Update-PodeWebTextbox -Name 'Date1' -Value '2023-02-08'
                Update-PodeWebTextbox -Name 'Date2' -Value '2023-02-08'
                Update-PodeWebTextbox -Name 'Date3' -Value '2023-02-08'
            ) 
        }
    )

    Add-PodeWebPage -Name 'Test' -Icon 'account-box-multiple' -Layouts $modal, $card -ScriptBlock {

    }
}
```

### Expected Behavior
All Input-Elements should be updated with the supplied value passed to the commandlet `Update-PodeWebTextBox`

### Screenshots
![image](https://user-images.githubusercontent.com/3882400/217588797-114ff5fe-5d45-4dac-838a-234971857a9a.png)

### Platform
 - OS: Windows
 - Browser: Edge Chromium 109.0.1518.78 64bit
 - Versions:
   - Pode: 2.7.2
   - Pode.Web: 0.8.2
   - PowerShell: 7.3.2

**Comment by Badgerati** [comment]
Hi @frocentus,

The commit above now fixes `Update-PodeWebTextbox` to work with Date types. As for working with `New-PodeWebDateTime` this is expected since the function can render two textboxes for date and time; it'll need its own `Update-PodeWebDateTime` function - I'll raise another issue for it.
