### ISSUE TITLE
Add functions to further control Page Group functionality

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode.Web#435]
### Describe the Change
Add functions to further control Page Group functionality; for example: Icons, Display Name, Page Counters, etc.

This could be:
* `New-PodeWebPageGroup`
* `Get-PodeWebPageGroup`
* `Test-PodeWebPageGroup`

Since Groups currently are "setup" by directly passing `-Group` name to `Add-PodeWebPage`, we'll need to make sure backwards compat support works. Ie: if the group doesn't exist, just create a default Group via `New-PodeWebPageGroup`.

```powershell
New-PodeWebPageGroup -Name 'GroupName' -DisplayName 'Actual Name Displayed' -Icon 'cogs' -NoPageCounter

Add-PodeWebPage -Name 'PageName' -Group 'GroupName' -ScriptBlock { ... }
```

**Comment by Szeraax** [comment]
This is really cool. Subscribed to both of these issues now. Would help be useful on this issue? What things would you like help with if so?

**Comment by Badgerati** [comment]
Hey @Szeraax, sorry just saw this! With the commit I just pushed, other than migration guide and docs updates, the work for this issue should mostly be done now 😄

**Comment by Badgerati** [comment]
Extras introduced by this issue, because of the way the code was originally written:

* Removal of `Set-PodeWebHomePage` - this became completely redundant with custom paths on `Add-PodeWebPage`. You can flag a page created via `Add-PodeWebPage` to be a system home page via the `-HomePage` switch.
* `Use-PodeWebTemplates` has a `-RootRedirect` switch, which if supplied will build a default empty home page that just redirects to the root page
* You can customise the ordering of pages via `-Index` on `Add-PodeWebPage` - this ordering is done within the scope of a Grouping of pages
