### ISSUE TITLE
ActiveDirectory Find Users

### ISSUE THREAD

**Issue by RonniHartung** [Badgerati/Pode.Web#456]
### Question
A clear and concise description of your question.
I have create a page where we can search AciveDirecotry for users, Get-ADuser $username -Properties.

The issue is, that it only find/shows some accounts.
When searching for accounts i Powershell directly, the accounts exists, but can de found/shown on the Pode site.
I have tried to compare the users, which could be found, with no indication on what should be different.

Any idea what could be the issue.

**Comment by RonniHartung** [comment]
UPDATE
The users failing in org. question can be found by the following code:
    Add-PodeRoute -Method Get -Path '/api/users/:userId' -ScriptBlock {
        Write-PodeJsonResponse -Value @{
            #Name = $WebEvent.Parameters['userId']
            UserId = (Get-ADUser $WebEvent.Parameters['userId'] -Properties *)
        }
    } -PassThru |
    Add-PodeOAResponse -StatusCode 200 -Description 'A user object' -ContentSchemas @{
        'application/json' = (New-PodeOAObjectProperty -Properties @(
                #(New-PodeOAStringProperty -Name 'Name'),
            (New-PodeOAIntProperty -Name 'UserId')
            ))
    }

**Comment by Badgerati** [comment]
Hi @RonniHartung,

From https://badgerati.github.io/Pode/Getting-Started/KnownIssues/#activedirectory-modul, the usual culprit for AD module issues is the module isn't being imported first; one to check and ensure 😃 

If it is being imported, could it be:
* An access issue with the user that running your Pode site?
* What happens if you use the full LDAP path for the users that can't be found?

**Comment by RonniHartung** [comment]
I have tried to import ActiveDirectory, no change

The "funny" thing is that i can find some users from the same OU, as them that fails.
As mentioned, when i create a PodeRoute Get -Path '/api/users/:userId' i can find the users that "fails" in Pode.Web.

Next option is to call the create API in Pode.web, to get the information that is needed, if that works.

Update
Calling the API, where the data is found that is needed, does not help.
The wanted users is found in API, but is not shown in Pode.Web PodeWebTextBox
