### ISSUE TITLE
New-PodeWebTable Limits

### ISSUE THREAD

**Issue by Naseito** [Badgerati/Pode.Web#461]
I´m building a pode.web website to retrieve some logs from Azure Log Analytics Workspaces and show then in a pode.web table.

For that I build a module that retrieves the logs (Get-Logs function), filters them and return a pscustomobject to be used by New-PodeWebTable:

```
        New-PodeWebTable -Name 'BackOff' -SimpleSort -SimpleFilter -DataColumn "Pod Name" -Sort -Paginate -ScriptBlock {
            Get-Logs -Query "KubeEvents | where Reason == `"BackOff`""
        } 
```

For the example above works well. But when I change to another query that return more results (aprox 582) it keeps loading and nothing is displayed on the website. I tested on a terminal that the module and the other query were working fine, so clearly is related to New-PodeWebTable.

At first I thought it was due to the number of results, but if I export those results to csv first and then I load the csv with -CsvFilePath works fine:

My question is: Is there any limit on the time (or timeout) for passing the object to the table? If so, is there any way to overcome it?

Thanks for your help and support!

**Comment by Badgerati** [comment]
Hi @Naseito,

There is a default timeout on requests of 30 seconds, this can be customised in via a `server.psd1` config file: https://badgerati.github.io/Pode/Tutorials/RequestLimits/#timeout

Hope that helps! 😃

**Comment by Naseito** [comment]
Perfect, I will try this. I managed to solve it by leveraging some of the work I was doing with PS on the KQL query, but is good to have this option also available.

Thanks for taking the time to answer and for your hard work and dedication on pode, @Badgerati .
