### ISSUE TITLE
Upgrade Bootstrap framework to 5.x

### ISSUE THREAD

**Issue by IvanDrag0** [Badgerati/Pode.Web#503]
Per the Bootstrap [release info](https://github.com/twbs/release), version 4.x has reached EOL as of 01/01/2023. Pode.Web should start the process of transitioning to version 5.x due to new features and stability/bug/security updates.

**Comment by Badgerati** [comment]
I did start work for this in #56, it was just a lot more difficult than I'd original thought. I'm going to try again for v1, in case some of the difficulties were bugs in the original v5 release and have now been fixed.
