### ISSUE TITLE
Binding data to specific columns when updating tables

### ISSUE THREAD

**Issue by IvanDrag0** [Badgerati/Pode.Web#508]
I have a CSV import that I'm trying to format into a table on the page. I've created a form using `New-PodeWebForm` and I have the following table:

```
New-PodeWebContainer -Content @(

            New-PodeWebTable -Name 'Table' -Paginate -Filter -SimpleFilter -Compact -Columns @(
                Initialize-PodeWebTableColumn -Key 'ColumnA'
                Initialize-PodeWebTableColumn -Key 'ColumnB'
                Initialize-PodeWebTableColumn -Key 'ColumnC'
                Initialize-PodeWebTableColumn -Key 'ColumnD'
            )

        )
```

The CSV import has those columns in it but also a bunch of others that I don't need. I've tried using the `Update-PodeWebTable` (`$CSV | Update-PodeWebTable -Name 'Table'` and `Update-PodeWebTable -Name 'Table' -Data $CSV`), but neither method seems to work (it shows a table with all the columns in the CSV).

My questions are:

1. How would I go about updating the table with the CSV using only the columns in the table (so far, the only way I was able to do that is by "filtering" the CSV using `Select-Object`)?
2. Is it possible to display a column's header differently than what is in the input object/CSV (so that if the CSV has a column named "ColumnA", I'd like it to bind to ColumnA in the table, but show the header as "Column A")?

**Comment by Badgerati** [comment]
Hi @IvanDrag0,

For the first question, I was just going to recommend `Select-Object` myself - it's the usual way to filter out unwanted properties. As for your second question, yes it's possible, the `-Name` parameter on `Initialize-PodeWebTableColumn` lets you ass a custom name :)
