### ISSUE TITLE
V2.9.0 returning error on showserverdetails 

### ISSUE THREAD

**Issue by sylvainricher** [Badgerati/Pode.Web#521]
Hi,

After installing the Pode and Pode.Web modules with the following instructions:

Install-Module -Name Pode -Scope CurrentUser -FORCE
Install-Module -Name Pode.Web -Scope CurrentUser -FORCE

I got the following error:
The property 'ShowServerDetails' cannot be found on this object. Verify that the property exists and can be set.

My issue was resolved by importing the module from my previous version (2.8.0)
Import-Module -Name Pode, Pode.Web -MaximumVersion 2.8.0

**Comment by Badgerati** [comment]
Hi @sylvainricher,

This is expected if you've installed the new version of Pode within the same session of how you're running your server, and then started the server again. PowerShell will have cached the DLL Pode uses from 2.8.0, and it won't load the newer DLL without starting a new session.

For example, if you're running it in a PowerShell terminal you'll have to close the terminal and open it again.

Sadly there's nothing I can really do, as it's a quirk of PowerShell itself, and there's no way to un-cache the cached DLL once loaded.

Hope that helps!
