### ISSUE TITLE
Pages imported via Use-PodeWebPages do not use authentication even if set on startup

### ISSUE THREAD

**Issue by jaucay** [Badgerati/Pode.Web#523]
I am creating a tool that will will automate some backup related tasks for the company I work for. I want to require authentication to any page of the app using Entra ID (Azure AD). I was able to successfully set up authentication for the application on the Home/Dashboard page. To keep things clean, I wanted to keep the Pode web pages in their own file and import them using Use-PodeWebPages.  

If I import the pages in this manner, the main home page prompts the user to sign in. However, if a user manually navigates to a page (i.e. https://<your.site>:8080/pages/clients), they are able to view the contents of the page without authentication. If I move the entire Add-PodeWebPage command to the main initializing script instead of relying on Use-PodeWebPages, it does prompt for authentication.

Is this intended behavior? Am I missing something?

**Comment by Badgerati** [comment]
Hi @jaucay,

It's not intended behaviour, I'm not sure what could be happening there 🤔. Under the hood `Use-PodeWebPages` just dot-sources the file; what happens if you just dot-source the file normally, is the auth still missing?

**Comment by jaucay** [comment]
Hello and thank you for the reply @Badgerati.

So it seems the problem was the order where I was calling Use-PodeWebpages. [In the documentation](https://badgerati.github.io/Pode.Web/Tutorials/Pages/#webpage), it does not mention in what order to place the command, but I should've remembered that the order matters with PowerShell. As an example, if you don't put the function first before you call it, it will fail because it doesn't know the function exists until it reads it into memory. I think the same thing happened here, Because the auth scheme was called after Use-PodeWebPages, only the homepage got authentication.

This is the command order that ended up working for me:

1. Enable-PodeSessionMiddleware
2. New-PodeAuthAzureADScheme
3. Add-PodeAuth
4. Set-PodeWebLoginPage
5. Set-PodeWebHomePage
6. Use-PodeWebPages


Sorry for the simple mistake. Do you believe a note should be added to the docs for the future, or do you think the reference to this issue is enough?

**Comment by Badgerati** [comment]
Having reference to a solution in this issue should be enough 😃 as you say, order of commands is a default feature in PowerShell. If others raise similar issues I'll look at adding something into the docs then.
