### ISSUE TITLE
Tables: filter and pagination

### ISSUE THREAD

**Issue by kort3x** [Badgerati/Pode.Web#54]
Applying filters to paginated webtables returns only rows from the active table page.

**Comment by Badgerati** [comment]
Hey,

This one I am aware of, I'm hoping to look at it soon because it does annoy me at times as well! 😂

**Comment by augiaugi** [comment]
I am not sure if this comment is right on this issue but I cannot find any way to implement "server side pagination". Is this something you could please implement as in my opinion it is a must have for a lot of projects. :)

**Comment by Badgerati** [comment]
I'll see if it's something I can implement at the same time :)
