### ISSUE TITLE
Issues with Show-PodeWebColumn and Hide-PodeWebColumn

### ISSUE THREAD

**Issue by ThomasPerezBlanco** [Badgerati/Pode.Web#545]
Hello everyone,

I just tried the examples for the Show-PodeWebColumn and Hide-PodeWebColumn commands with the latest Pode.Web module.
It doesn't work.

Best regards,

Thomas

**Comment by Staples1887** [comment]
The examples have the wrong function name in the button's scriptBlock. They are missing the word table, so should be changed to Hide-PodeWeb***Table***Column and Show-PodeWeb***Table***Column

**Comment by ThomasPerezBlanco** [comment]
It works, thanks for your help.
