### ISSUE TITLE
Add -Disabled switch to New-PodeWebSelect command

### ISSUE THREAD

**Issue by ml222** [Badgerati/Pode.Web#562]
### Describe the Change
Would be great if the New-PodeWebSelect command had a -Disabled parameter, just like the commands New-PodeWebCheckbox and New-PodeWebButton have. Perhaps that would also lead to the need for Enable-PodeWebSelect and Disable-PodeWebSelect commands.

**Comment by Badgerati** [comment]
This has already been done, and will be in Pode.Web v1.0 :) `Update-PodeWebSelect` has also been updated to support toggling state as well

https://github.com/Badgerati/Pode.Web/blob/ca32738a1636ce7d9e8e1ab35255bb576a31ba9f/src/Public/Elements.ps1#L503-L506

I do like the idea of specific `Enable-PodeWebSelect` and `Disable-PodeWebSelect` functions though

**Comment by ml222** [comment]
Ok, I didn't know that, but that's great! Thanks.
