### ISSUE TITLE
New-PodeWebButton not working on Linux Container

### ISSUE THREAD

**Issue by weiyentan** [Badgerati/Pode.Web#563]
### Describe the Bug
Using New-PodeWebButton works as expected in a VM or physical machine as below:
``
 new-podewebbutton -Name test -ScriptBlock {
                    Show-PodeWebToast -Message "Job finished successfully!" -Duration 10000
                }
``

Running this block of code in a container does not do anything.
 
### Steps To Reproduce
Create New-PodeWebutton and run in container. It does not execute the code in the script block

### Expected Behavior
I expect that the code in the scriptblock runs as it does on a vm or physical machine.

### Screenshots
n/a

### Platform
 - OS: container (linux)
 - Browser: Edge
 - Versions:
   - Pode.Web: [e.g. Pode.Web v0.8.3]
   - PowerShell: [e.g. PS7.x]

### Additional Context
This has been tried on VM (works) / Podman(does not work)/ kubernetes (does not work)

**Comment by Szeraax** [comment]
I have been unable to reproduce this. Running in a container, the toast works fine.

**Comment by weiyentan** [comment]
> I have been unable to reproduce this. Running in a container, the toast works fine.

thanks for checking this out. i have done the same test and it works fine too. so i'll continue to test and try to see if i get similar issues again. thanks for the help
