### ISSUE TITLE
Pode.Web 1.0.0 Preview 2 - Web Pages Don't Display the Same as 0.8.3

### ISSUE THREAD

**Issue by jbaechtelMT** [Badgerati/Pode.Web#601]
### Describe the Bug
Simple web page doesn't display the same as it does under **Pode.Web v0.8.3** when using **Pode.Web Preview-2 v1.0.0**.  **_Many page elements are missing or misplaced on the page_**.

### Steps To Reproduce the behavior:
1. Run the following code (**Note**: **_Not all of the code displays inside of the code block below, some lines display above the code block_**.  **Please make sure you get it all when copying**.
2. View **Home Page**:  **[http://localhost:8080/pages/Home](http://localhost:8080/pages/Home)**
3. **Un-comment line 4** to use Pode.Web module **v1.0.0**
4. Run the code
5. View Home Page: **[http://localhost:8080/pages/Home](http://localhost:8080/pages/Home)**
6. See the vast differences (**missing elements** and **different positioning on page**) in the **Home Page** using **version 1.0.0**

### Page Code
`CLS
$PodeVersion = '2.10.1'
$PodeWebVersion = '0.8.3'
#$PodeWebVersion = '1.0.0'

If (Get-Module -Name 'Pode') {Remove-Module -Name 'Pode' -Confirm:$false -Force}
Import-Module -MaximumVersion $PodeVersion -MinimumVersion $PodeVersion -Force:$true -Name 'Pode'
Write-Host "`n          Import-Module -MaximumVersion $PodeVersion -MinimumVersion $PodeVersion -Force:$true -Name 'Pode'"

If (Get-Module -Name 'Pode.Web') {Remove-Module -Name 'Pode.Web' -Confirm:$false -Force}
Import-Module -MaximumVersion $PodeWebVersion -MinimumVersion $PodeWebVersion -Global:$true -Force:$true -DisableNameChecking:$true -Name 'Pode.Web'
Write-Host "`n          Import-Module -MaximumVersion $PodeWebVersion -MinimumVersion $PodeWebVersion -Force:$true -Name 'Pode.Web'"

Start-PodeServer -Threads 10 -EnableBreakpoints -StatusPageExceptions 'Show' -Name 'default' -ScriptBlock {

	New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging

	Add-PodeEndpoint -Protocol 'Http' -Port 8080 -Default -Force -Address 'localhost' -Name 'local'

	Use-PodeWebTemplates -Theme 'Light' -Title 'Pode YAML Config'

	Add-PodeWebPage -NoAuthentication -Title 'Launch Pode From YAML Config' -Name 'Home' -ScriptBlock {
		New-PodeWebCard -Name Hello -Content @(New-PodeWebText -Alignment Right -Style Bold -Value 'Hello!')}}`

### Expected Behavior
**Pages should display the same with no missing element**s.

### Screenshots
**Pode.Web v0.8.3**:

![image](https://github.com/Badgerati/Pode.Web/assets/107774312/79ad4096-e296-4372-9b49-8febb4f79045)

![image](https://github.com/Badgerati/Pode.Web/assets/107774312/25e5aacf-b543-460d-ae6c-1d75a43d73f9)

**Pode.Web Preview 2 v1.0.0**:

![image](https://github.com/Badgerati/Pode.Web/assets/107774312/8009c813-53f6-4da0-b580-db7f0048202f)

![image](https://github.com/Badgerati/Pode.Web/assets/107774312/0f20bee6-12f3-44d2-8896-18dffaa1fff5)

### Platform
 - OS: **Windows 11**
 - Browser: **Chrome**, **Safari**, **Edge**, and **Firefox**
 - Versions:
   - Pode: **v2.10.1**
   - Pode.Web: **v0.8.3** and **v1.0.0**
   - PowerShell: **v5.1** and **v7.4.2**

### Additional Context
N/A.

**Comment by Badgerati** [comment]
Hi @jbaechtelMT,

I've tested myself locally and both versions load as expected for myself; the following image is when using 1.0.0-prevew2:
![image](https://github.com/user-attachments/assets/fb28b81c-28ed-4e3d-924f-23398c59979c)

It looks like it might be trying to use cached versions of 0.8.3 scripts/styles, so might be worth trying to clear you cache and/or refreshing with Ctrl+F5. If it still doesn't load properly, press F12 and inspect the developer Console tab for any loading errors.

**Comment by jbaechtelMT** [comment]
@Badgerati

Thanks for looking at this issue:

When I ran the developers tools in the browser I got several errors for CSS files not loading (see screenshot below).

![image](https://github.com/user-attachments/assets/8a2d8794-b8bb-457d-ba54-0532600552fb)


I found that there were **two folders missing** from the **Pode.Web** modules folder (**C:\Program Files\WindowsPowerShell\Modules\Pode.Web\1.0.0\Templates\Public**).  These two folders: **libs** and **min-map** were the two folders **missing**.  I founds the missing files/folders in **Pode.Web v.0.8.3** module and copied them to the **Pode.Web 1.0.0** location.  **Web page display was improved but still not right** (see below).

![image](https://github.com/user-attachments/assets/a8e261ba-371b-4bbd-b8f7-b0e0ed5461a3)


So I went back to the developers tools in the browser and found other missing files causing failed loads:

![image](https://github.com/user-attachments/assets/299fc227-c4db-49ac-9bf7-66c589298a90)


I was unable to find them anywhere on my system so I was unable to copy them from another location to see if these are the only ones missing.

Thanks again for looking into this.  Keep up the good work!

**Comment by Badgerati** [comment]
Hi @jbaechtelMT,

It might be worth uninstalling and re-installing the Pode.Web module, as I think something might have gone wrong during the install.

Locally, and on the PowerShell Gallery, those two folders exist in 1.0.0 - and with all the required libs as well:
![image](https://github.com/user-attachments/assets/3b9576df-d0ad-4a78-9dbf-bd202463db3b)
![image](https://github.com/user-attachments/assets/aff7c5d5-d223-4328-a819-9f38985176ad)

Copying them from 0.8.3 wouldn't fully work either, as all the javascript/css libraries have been updated/changed in 1.0.0 - most notably going from Bootstrap 4 to Bootstrap 5.

**Comment by jbaechtelMT** [comment]
@Badgerati

Thanks for the support, that worked.

Originally I couldn't install the module since it was a pre-release version, it would only install up to v0.8.3 - I didn't know about the -AllowPreRelease parameter on the Install-Module command (only works in PS v7.4 and above).  So I created the module folder from the Zip download from the Github repository.  That's where things went wrong because the SRC directory in that Zip file doesn't contain those files/folders.

Please consider this closed and Thanks again.  Great product...
