### ISSUE TITLE
PodeWebTextBox with Autocomplete on NoAuth-Page

### ISSUE THREAD

**Issue by frocentus** [Badgerati/Pode.Web#62]
Hi, 

just stumbled over this while playing around with a Form:

I have added an WebPage (with -NoAuth option set) with a Form, on this Form is a Textbox wich has a simple Autocomplete (just returns an Array of Strings).

On loading, I get an Error in the file 'default.js' for the js-function 'sendAjaxReq'in the Browser-Javascript Console, that the returned JSON is not parsable, and in fact it gets HTML to parse from the server.

The HTML returned is the Login-Page, because the POST-Request to 'textbox_fraction' gets redirected (302) to the Login-Page.

I am on the current version (0.4.1) of PodeWeb.

**Comment by Badgerati** [comment]
Hey @frocentus,

Just got round to looking into this, did you also supply `-NoAuth` to `New-PodeWebTextbox` as well?

**Comment by frocentus** [comment]
Hi, thank you for your response - indeed that `-NoAuth` was missing on the TextBox. I added that and in works like a charm.
