### ISSUE TITLE
New-PodeWebTimer - Allow intervals lower than 10

### ISSUE THREAD

**Issue by tmolbergen** [Badgerati/Pode.Web#623]
### Describe the Change
New-PodeWebTimer is currently constrained to allowed being ran at the lowest of 10 seconds. Would it be possible to add an -Unsafe switch to allow lower intervals

### Related Issues
No specific issue

### Additional Context
I added a function inside the Pode.Web.Timer which removed the sanity check and the function that I run seems to work OK. For context sake what im trying to do is to update a Pode Webtable with the use of the timer with output of the Functions being ran by a WebForm, since the WebForm is a 'long' running task with alot of output, it would be nice to be able to display the current status of the long running task.

**Comment by Badgerati** [comment]
I've removed the restriction completely, and added a working to the docs :)
