### ISSUE TITLE
Add way to invoke web redirection or opening a url in a new page.

### ISSUE THREAD

**Issue by the-mentor** [Badgerati/Pode.Web#71]
Hi @Badgerati,

Awesome project !!

I'm working on migrating my site [PowerShellOnLinux](https://www.powershellonlinux.com) to Pode.Web since UD is end of life.

I have the source code to the site here https://github.com/the-mentor/PowershellOnLinux.com-Website

In UD there was a concept of Invoke-UDRedirect which will allow you to either redirect the current site or open a URL in a new window which was really useful.

Here is an example of how I used it
```
Invoke-UDRedirect -Url "https://t.me/PowershellOnLinux" -OpenInNewWindow
```

Let me know if it makes sense.
Thanks.

-DM

**Comment by Badgerati** [comment]
Hey @the-mentor, and thanks! 😄 

Pode.Web does have something similar, with the `Move-PodeWebUrl` output action:

```powershell
New-PodeWebButton -Name 'Click Me' -ScriptBlock {
    Move-PodeWebUrl -Url 'https://t.me/PowershellOnLinux'
}
```

The only thing it doesn't do is open the URL in a new window (I'm guessing this is a new tab? Or  was it a whole new chrome window?). So could definitely look to add that in :)

**Comment by the-mentor** [comment]
@Badgerati it opened the link in a new tab.

**Comment by Badgerati** [comment]
The commit above now makes it so that `Move-PodeWebUrl -Url 'https://t.me/PowershellOnLinux' -NewTab` is possible.

Likewise on a button that's just a URL as well: `New-PodeWebButton -Url 'https://t.me/PowershellOnLinux' -NewTab`

**Comment by the-mentor** [comment]
@Badgerati thanks for implementing this!

Would it be possible to use it in a "page" link?

What I mean is have a link under the pages nav bar that would just open a link in a new tab?

**Comment by Badgerati** [comment]
@the-mentor Do you mean letting the Page links in the sidebar, or the links you can add to the top navbar, open in a new tab? Or is it something else?

**Comment by the-mentor** [comment]
@Badgerati the links in the top navbar have support for script block.

But I was referring to the links on the sidebar in my last question

**Comment by Badgerati** [comment]
Aaah, yeah it should be possible to make those open in a new tab - something like `Add-PodeWebPage -NewTab`, I'll have a look

**Comment by the-mentor** [comment]
@Badgerati juat to be clear I don't want an actual page.
I want to have a link in the left bar that when I click on it it will run a script block.

So I can run something like the below code  when it's clicked. 

Move-PodeWebUrl -Url 'https://t.me/PowershellOnLinux' -NewTab

Does that make sense?

**Comment by Badgerati** [comment]
@the-mentor, Oh I see! Right, I get you now.

So really something like an `Add-PodeWebPageLink`, that works just like a button, and lets you do output actions - like redirecting.

**Comment by the-mentor** [comment]
> @the-mentor, Oh I see! Right, I get you now.
> 
> So really something like an `Add-PodeWebPageLink`, that works just like a button, and lets you do output actions - like redirecting.

That's correct!

**Comment by Badgerati** [comment]
@the-mentor, added `Add-PodeWebPageLink` which adds a page link to the sidebar:

```powershell
Add-PodeWebPageLink -Name Twitter -Icon Twitter -ScriptBlock {
    Move-PodeWebUrl -Url 'https://twitter.com' -NewTab
}
```
