### ISSUE TITLE
-NoTitle in New-PodeWebCard doesnt seem to work.

### ISSUE THREAD

**Issue by the-mentor** [Badgerati/Pode.Web#72]
As the title of the issue says when using -NoTitle in New-PodeWebCard its still showing the title of the card.

**Comment by ili101** [comment]
Hi @Badgerati 🙂, maybe something this will be more appropriate/intuitive https://github.com/ili101/Pode.Web/commit/6320a0c581552c5d7d6e743b522f2157e30ff608? so:
```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http

    Use-PodeWebTemplates -Title 'Example' -Theme Light

    Add-PodeWebPage -Name 'Services' -NoTitle -Icon 'Settings' -ScriptBlock {
        New-PodeWebCard -Content @(
            New-PodeWebParagraph -Value 'Card'
        )
        New-PodeWebCard -Name Named -Content @(
            New-PodeWebParagraph -Value 'Card'
        )
        New-PodeWebCard -NoTitle -Content @(
            New-PodeWebParagraph -Value 'Card'
        )
        New-PodeWebContainer -Content @(
            New-PodeWebParagraph -Value 'Container'
        )
    }
}
```
Will make:
![image](https://user-images.githubusercontent.com/6960531/121187775-15f26980-c871-11eb-8bcc-92abbf215804.png)

Also something i noticed is that in "Dark" Container and Card are the same but in "Light" the background is different:
![image](https://user-images.githubusercontent.com/6960531/121188002-55b95100-c871-11eb-94bf-91fc62ccb855.png)

**Comment by the-mentor** [comment]
also @ili101 @Badgerati i think an option to hide the "hide" button is also important maybe -NoHide or something like that 

since sometimes you might want to have a card with a title but no option to hide it.
maybe this should be a new issue idk

**Comment by ili101** [comment]
Maybe like this... https://github.com/ili101/Pode.Web/commit/5b5f654d313151a5f44c7750ff1d10f29e2f3a94
```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http

    Use-PodeWebTemplates -Title 'Example' -Theme Light

    Add-PodeWebPage -Name 'Services' -NoTitle -Icon 'Settings' -ScriptBlock {
        New-PodeWebCard -Content @(
            New-PodeWebParagraph -Value 'Card'
        )
        New-PodeWebCard -Name Named -Content @(
            New-PodeWebParagraph -Value 'Card'
        )
        New-PodeWebCard -NoTitle -Content @(
            New-PodeWebParagraph -Value 'Card'
        )
        New-PodeWebCard -NoHide -Content @(
            New-PodeWebParagraph -Value 'Card'
        )
        New-PodeWebCard -NoTitle -NoHide -Content @(
            New-PodeWebParagraph -Value 'Card'
        )
        New-PodeWebContainer -Content @(
            New-PodeWebParagraph -Value 'Container'
        )
    }
}
```
![image](https://user-images.githubusercontent.com/6960531/121201194-01b46980-c87d-11eb-9d82-70b6d6717705.png)

**Comment by Badgerati** [comment]
I like it! Very nice @ili101 😄 

And yeah you're right, the card/container backgrounds are subtly different - don't think I would've ever spotted that! 🕵️
