### ISSUE TITLE
Add CssStyle parameters to Elements/Layouts

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode.Web#89]
A new `-CssStyle` parameter can be added to Elements/Layouts, alongside `-CssClass`. This will access a hashtable of CSS style attributes that will be applied directly to the Elements/Layouts, such as:

```powershell
New-PodeWebButton -Name 'Example' -ScriptBlock {} -CssStyle @{
    'background-color' = 'pink'
}
```

which will add `background-color:pink;` to the button's `style` attribute.

**Comment by eugen257** [comment]
Hi @Badgerati,

how does it work with `New-PodeWebText` ?

for example: 
New-PodeWebText -Id "text" -CssStyle @{'text-align'='center'} -Value "TEST TEXT"
